---
title: "Seminar 2 General Info"
editor: visual
---

**Seminar 2: People of New York City** is explored in new ways every semester by cohorts of Macaulay Honors student. It will be helpful for our own exploration to learn from prior classes. [General information about seminar 2](https://eportfolios.macaulay.cuny.edu/faculty/2021/06/03/seminar-2-description-and-objectives/) is available from the Macaulay e-portfolio site. Many previous versions of the course and their resulting course projects are available from [the seminar 2 Encyclopedia](https://eportfolios.macaulay.cuny.edu/encyclopedia/category/all-the-sites/).

The purpose of this page is to collect information about seminar 2 that can help us better inform our own process for exploration and scholarship.

## Catalogue Description

In this seminar, students use tools from the social sciences, from oral history to mapping and participant observation and beyond, to investigate how the diverse people of New York City shape its identity, past, present, and future. Extensive reading and writing assignments are enriched by visits to neighborhoods, museums and historical and cultural sites across the city.

## Course Description

In this seminar, students use the tools of the social sciences, from oral history to mapping and participant observation and beyond, to investigate how the diverse people of New York City shape its identity, past, present, and future. Seminar topics include: the experiences of Indigenous and enslaved populations; the ongoing consequences of settler colonialism; the ways in which culture, class, religion, race, gender, ethnicity, xenophobia, and racism have shaped New Yorkers' experiences with and within the city; the formation and social organization of New York's communities; the impact of successive waves of newcomers to the city on urban culture and politics; and the continuing debates over assimilation, cultural retention, and "Americanization." Extensive reading and writing assignments are enriched by visits to neighborhoods, museums, and historical and cultural sites across the city and the use of demographic, population and other quantitative data as well as qualitative approaches. All classes create public-facing final projects, documenting their research and presenting an aspect of New York City's diversity.

## Learning Goals/Outcomes

Students will:

-   Demonstrate a comparative understanding of different populations through research and writing about one or more groups or about an area of the city and its shifting population across time.
-   Use a variety of approaches (e.g. qualitative, quantitative, or experiential) to studying people in order to come to an understanding of the diversity of people's experiences in and of the city.
-   Understand the advantages and disadvantages of different approaches and methodologies used by the social sciences.
-   Increase their understanding of past and present issues including colonialism, migration, immigration, race, and ethnicity by analyzing a variety of sources (current, historical, primary, secondary) and by engaging in active discussion about those issues.
-   Present their research to a public audience through a final project that may be completed by small groups or the entire class.
-   Critically examine their own roles in and effect on the communities of New York City.

## More context for Seminar 2

Faculty who teach seminar 2 receive information packets about this seminar. I am sharing some of this info here to provide more context for the course.

'The course was originally titled "The Peopling of New York City," and focused on patterns of immigration as well as neighborhood constitution and dynamics. In conversations with faculty, students and ITFs/TLCs, we've moved towards a slight modification to that title. "The People of New York City" more accurately reflects the content the course should cover. Immigration is not an unqualified positive story, and the story of the people of New York includes indigenous populations (past and present), as well as those whose ancestors (near or far) were brought to New York without choosing to come voluntarily. Questions of gentrification, race, culture, gender, homelessness, inequality, education, cultural appropriation (and more) can all be part of the content of this course, and the narratives that the course pursues are complex and multifaceted.'

"This is an interdisciplinary course, and should be taught as such. It is not a history course, a sociology course, or an anthropology course, but it often has elements of all of those fields. It should not be seen as an introductory course to any specific field, but instead a cross-disciplinary examination of the ways that different areas in the social sciences might approach the same content area. The course should provide some comparison of different approaches in every individual section. Sociology, anthropology, history, political science, geography, demographics (and more) are all welcome, but no single one of these areas should be the sole focus of the course."

## Honor's expectations

This is an honors seminar, and as a class we will discuss and develop expectations for honors level work. This will generally entail "a deep and critical understanding of source material, and a creative and fluent expression of the products of research". We will creatively explore many ways to engage in and express honors level inquiry.

## The common project

"The course requires a public-facing project of some kind from all students. Many sections have produced a website detailing their research on a neighborhood or an immigrant group (or some other topic). You can find many examples on the TLC site. A website project remains a very strong and effective way of fulfilling the public-facing project requirement of the course, especially during distance learning. There are other alternatives, such as videos, that some classes have experimented with. Those projects still need an online presence as a way of being shared and publicly accessible."

Examples of past projects can be seen in the [Seminar 2 encyclopedia](https://eportfolios.macaulay.cuny.edu/encyclopedia/category/all-the-sites/).

We will be discussing and developing our own common project throughout the semester that will, at a minimum, involve developing a website to present a public-facing expression of our seminar 2 activities.
