project:
  type: website

website:
  title: "peopleofnyc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
    right: 
      - about.qmd
      
format:
  html:
    theme: quartz

editor: visual

