project:
  type: website
  output-dir: docs

website:
  title: "peopleofnyc"
  image: "imgs/nyc.png"
  description: "Website for Seminar 2: People of New York City, Spring 2023. Taught by Dr. Matthew Crump at Brooklyn College of CUNY."
  repo-url: https://github.com/CrumpLab/peopleofnyc
  repo-actions: [source, edit, issue]
  search: true
  twitter-card:
    creator: "@MattCrumpLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "The Remembering Project"
        file: project/intro.qmd
    right: 
      - about.qmd
      - text: "Quarto Examples"
        menu:
          - example_pages/quarto_help.qmd
          - example_pages/quarto_about_trestles.qmd
          - example_pages/quarto_about_jolla.qmd
          - example_pages/quarto_about_solana.qmd
          - example_pages/quarto_about_marquee.qmd
          - example_pages/quarto_about_broadside.qmd
          - example_pages/quarto_none.qmd
          - example_pages/quarto_theme.qmd
          - example_pages/people_page_1.qmd
      - icon: github
        href: https://github.com/CrumpLab/peopleofnyc
        aria-label: GitHub
  sidebar: 
    - title: "The Remembering Project"
      style: "floating"
      collapse-level: 2
      align: left
      contents: 
        - project/intro.qmd
        - project/1_chpt.qmd
        - project/2_chpt.qmd
        - project/3_chpt.qmd
        - project/4_chpt.qmd
        - project/5_chpt.qmd
    - title: "Quarto Examples"
      
format:
  html:
    theme: cosmo
    css: css/nav.css
    toc: true

editor: visual

