project:
  type: website
  output-dir: docs

website:
  title: "peopleofnyc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
    right: 
      - about.qmd
      - text: "Quarto Examples"
        menu:
          - example_pages/quarto_help.qmd
          - example_pages/quarto_about_trestles.qmd
          - example_pages/quarto_about_jolla.qmd
          - example_pages/quarto_about_solana.qmd
          - example_pages/quarto_about_marquee.qmd
          - example_pages/quarto_about_broadside.qmd
          - example_pages/quarto_none.qmd
          - example_pages/quarto_theme.qmd
      
format:
  html:
    theme: none
    css: css/nav.css

editor: visual

