---
title: "Greenwood Cemetary"
author: "Carina Alessandro"
---

Green-Wood Cemetery was founded in 1838 helped start the trend for rural cemeteries when the dead that were usually buried in church yards or potter’s fields lacked burial space and a certain quiet aesthetic people started to crave in the early 19th century. It also set a trend for public parks because of its features that led families in the 1860s to frequent only second to the Niagara Falls the most popular tourist attraction in the nation at the time.
However, people don’t only come to Green-Wood only for its 478 acres, seven thousand trees, 216 feet above elevation, or (quite frankly; no offense) 600,000 graves. In the 19th century, families went on outings at the cemetery for carriage rides and sculpture viewing— and it’s not much different today.

The sculptures in question refer to the opulent, historic architecture contained on its land. Those rich enough commissioned the architects (which were oft renown, such as the designer of Grand Central Terminal) of their own estates to build eclectic monuments rather than just gravestones to house and mark their eternal homes. Within the gothic reviving cemetery gates Greek temples, Renaissance palaces, Egyptian temples, Corinthian columns, obelisks, and any variety of Disneyland-like scaled mausoleums and vaults, sat inside. There used to be fifty graves made a day by a multitude of gravediggers, but despite its acreage, the cemetery almost named “Necropolis,” can now only make room for a handful of dead per day. With dwindling space— family members share plots and are laid to rest on top of each other— and the more economical cremation on the rise, there’s fewer new residents to the rural community. Still, its admittedly livelier, curious visitors haven’t been found themselves unwelcome yet.

Thanks to the nonprofit cemetery’s Historic Fund established in 1999, Green-Wood now homes a seven hundred-or-so-piece art collection of the many artists buried there (such as Jean-Michael Basquiat— though he’s not featured, as they must rely on more affordable and lesser known, but representative paintings) in its office and art installations. However, installations weren’t exclusive to the nonliving, but also to modern artists too, who wished to have their art in a catacomb, for example. Furthermore, posthumous notoriety wasn’t limited to artists, but a few Civil War soldiers and sailors and a couple hundred baseball pioneers as well. Though carriage rides are no longer readily available, the historic landmark’s fund continues to host tours and seasonal events open to the public to to this day.

Sources:

[https://www.green-wood.com/about-history/](https://www.green-wood.com/about-history/)

[https://www.nytimes.com/2006/01/30/nyregion/the-ones-who-prepare-the-ground-for-the-last-farewell.html](https://www.nytimes.com/2006/01/30/nyregion/the-ones-who-prepare-the-ground-for-the-last-farewell.html)

[https://www.nytimes.com/2008/12/07/nyregion/07greenwood.html](https://www.nytimes.com/2008/12/07/nyregion/07greenwood.html)

[https://www.mcny.org/exhibition/beautiful-way-go](https://www.mcny.org/exhibition/beautiful-way-go)

[https://www.nytimes.com/1977/11/17/archives/design-notebook-pastoral-greenwood-cemetery-is-a-lesson-in.html](https://www.nytimes.com/1977/11/17/archives/design-notebook-pastoral-greenwood-cemetery-is-a-lesson-in.html)

further reading: [https://www.nytimes.com/2004/04/01/nyregion/ground-hallowed-cooperstown-green-wood-cemetery-home-200-baseball-pioneers.html](https://www.nytimes.com/2004/04/01/nyregion/ground-hallowed-cooperstown-green-wood-cemetery-home-200-baseball-pioneers.html)
