---
title: "The Brooklyn Heights Promenade"
author: "Vanessa Cruz"
---

The Brooklyn Heights Promenade, measures roughly 1800 feet and, is a free public space that offers an incredible view of Downtown Manhattan, the East River and Brooklyn Bridge. Tourists are attracted to this area because of these views as well as the surrounding neighborhood, which accompanies beautiful brownstone houses and healthy trees. The promenade mostly attracts joggers and families. Besides being famous for its view it is also famous for three monuments. Its most famous is the flagpole at the bottom of Montague Street in tribute to Genevieve Beavers Earle (1885-1956), a Brooklyn Heights resident and civic leader. Earle was the first woman to serve in the New York City Council and was an independent republican who fought for the creation of playgrounds and recreational centers. The Promenade opened to the public in 1827 and later in 1952, became popular as a gay dating site, which was not immediately accepted by local residents. Due to this, the Promenade is also recognized as a LGBT historic landmark. 

Robert Moses was head of construction for New York City’s housing authority and wanted to build a multilane of highways to connect the five buroughs. However, after there was a great amount of public opposition, the location of the multi-lane highways that began construction in 1939, was moved to the western end of the neighborhood. Later in 1946, Gilmore Clarke and Michael Rapuano, two landscape architects, constructed the 11.7 mile expressway and 1,826 foot long Promenade we know today. The walkable public parkway was constructed along the East River escarpment, saving space and minimizing intrudement into the surrounding Brooklyn Heights neighborhood. The Promenade opened in 1950 and is edged with fencing and currently has benches where visitors can sit along the walkway. By 1952, The promenade had become a site for gay male cruising. In the early 1960’s, it attracted gay men from all over the city. Armand Whitehead, a man who moved to Brooklyn Heights in 1963, said “It was absolutely wild. People did everything there.” 

Currently, the promenade is no longer a site where gay men prefer to cruise the same way they did in the 1950’s and 60’s. However, it is still loved by many residents in the community. The Promenade overlooks the basketball courts at Brooklyn Bridge Park and is a perfect place to go when weather is nice, especially if you are hoping for a spectacular view. It’s featured in many guidebooks, like Trip Advisor, Trip Savvy and NYCgo.com. The Brooklyn Heights Promenade is a location that remains loved by its residents and tourists from all over the world.

Adams, Rose. “How Brooklyn Women Paved the Way for Women in Politics.” Brooklyn Paper, March 29, 2021. [https://www.brooklynpaper.com/brooklyn-paved-the-way-women-in-politics/](https://www.brooklynpaper.com/brooklyn-paved-the-way-women-in-politics/).

“Brooklyn Heights Promenade: Attractions in Brooklyn, NY.” [NYCgo.com](http://nycgo.com/). Accessed May 17, 2023. [https://www.nycgo.com/venues/brooklyn-heights-promenade/](https://www.nycgo.com/venues/brooklyn-heights-promenade/).

“Brooklyn Heights Promenade.” NYC LGBT Historic Sites Project. Accessed May 17, 2023. [https://www.nyclgbtsites.org/site/brooklyn-heights-promenade/#:~:text=The Promenade%2C a pedestrian walk,gay male cruising by 1952](https://www.nyclgbtsites.org/site/brooklyn-heights-promenade/#:~:text=The%20Promenade%2C%20a%20pedestrian%20walk,gay%20male%20cruising%20by%201952).

“Historical Sign Listings : NYC Parks.” Brooklyn Heights Promenade. Accessed May 17, 2023. [https://www.nycgovparks.org/about/history/historical-signs/listings?id=136](https://www.nycgovparks.org/about/history/historical-signs/listings?id=136).

“New York City’s Landscape Legacy.” TCLF. Accessed May 17, 2023. [https://www.tclf.org/brooklyn-heights-promenade#:~:text=Designed in 1946 by Clarke,the surrounding Brooklyn Heights neighborhood](https://www.tclf.org/brooklyn-heights-promenade#:~:text=Designed%20in%201946%20by%20Clarke,the%20surrounding%20Brooklyn%20Heights%20neighborhood).