---
author: "Maxwell Hecht-Chaneski"
title: "Borough Hall Greenmarket"
---

The Borough Hall Greenmarket is one of the many independently owned farmers’ markets serving New York City. It is a relatively popular market for buying and selling fresh produce, partially due to its placement in Borough Hall. The location itself includes a wide space for setting up tents and accommodating places for relaxation and recreation. These markets are founded by the local nonprofit organization GrowNYC.

GrowNYC is dedicated to targeting and eliminating food waste across New York City. Their main office is stationed in Manhattan, 100th Gold street. GrowNYC was originally known as the Council on the Environment of New York City, and was founded as a policy organization in 1970. It established an environmental program called the Green Market Program in 1976, and provided producers only farmer’s markets weekly across the entirety of New York. Years later in 2007, it also started initiating programs directly funded by the NYC Department of Sanitation, including initiatives that educate children on the importance of conservation and recycling. They have worked to make sure that every school in New York City has some kind of a garden.

The Borough Hall Greenmarket has become one of the most important public spaces in downtown Brooklyn and beyond. The market is open year round on Saturdays from 8 AM to 3 PM, and Tuesdays, seasonally. Composting hours are 8 AM -12. Many locals take part in the program. New to the initiative is that compost from the program will be brown bagged and offered back to the community for gardening. Brooklyn buildings have many front garden areas, window boxes, and stoop planters. Less known to visitors is that the backs of buildings are a greenspace, in many places in Brooklyn, and those who have access may do a lot of gardening there.

The vendors at Borough Hall Greenmarket change from week to week but a common array of specialties might include wild-caught fish from Long Island; honey from Delaware County, NY; artisan breads from Ulster County, NY; and farm produce from New York and New Jersey, including fruit, vegetables, meat, jams, cheese, and flowers.

In early summer, before the fruit and vegetable are plentiful, the farm stalls can be found selling seedlings of all kinds of vegetable and flowering plants. Unlike many farmers’ markets, Borough Hall Greenmarket doesn’t pack up and leave at the end of summer, but goes all year long. In winter it is much smaller, of course, selling apples and potatoes, honey, bread, jarred vegetables, and fish and meat, both wild caught and farm raised. There are also hot meals which can be eaten there, including meat pies, spinach and cheese pastries, and vegan options. The sellers can heat these up to eat there, or package some up to take home. The people selling food there are often the people who worked on the farm and especially when they are cold and standing there in bad weather, the community is grateful for the fresh food and is glad to also be able to help support the local farms.

[https://www.grownyc.org](https://www.grownyc.org/)

https://www.bbb.org/us/ny/new-york/charity-review/charity-environment/grownyc-0121-154248

https://nooklyn.com/stories/grownyc-and-the-changing-food-movement-of-new-york-city

https://www.rit.edu/sustainabilityinstitute/public/academic/Urban_Food_Waste_Workshop_Report.pdf

https://www.wnyc.org/story/50th-anniversary-grownyc/