---
author: "Maxwell Hecht-Chaneski"
title: "Cobble Hill Park"
---

Cobble Hill Park is a small communal park in west Brooklyn, nestled under Manhattan and situated between Veranda Plaza and Congress St. It takes up half of the block it resides in. It has a small playground, an ovoid path in the center for walks, and public tables at the main entrance, along with an elevated flower bed.

Cobble Hill Park is especially notable for its creation in the 1960’s, originally being the location of the Whitten and Weber mansions, as well as an abandoned Unitarian Church. These mansions were demolished as the land was purchased by the Bohack corporation, which specialized in chain grocery stores starting in 1887 and ending in
1977. The Bohack corporation planned on building a supermarket in the mansions’ place, but the Cobble Hill Association collaborated against it in favor of a park. The space was then bought by private builders, who planned to build a six-story apartment, but the Local neighborhood united to cancel this project, which resulted in the construction of the park.

The neighborhood itself had low buildings and so provided a space with abundant sunlight and air, and this act against the construction of these buildings helped preserve that open environment in a city with air and light deficiency. The park provided a place to enjoy this sunlight and air as well, establishing the neighborhood that fostered it as a strong and healthy community.

The Cobble Hill Park is lined on one side with a low row of old houses, many of them converted carriage house. The combination of the manicured park and this row of old- world looking houses has ensured that many films have included the park and the row of houses, called Veranda Place. Such movies might be showing an ideal New York City, or in disguise as a street in a town in some European country.

The park has a playground at one end with a great sculpture of a dolphin at the center of a sandbox, there are a few slides and a giant spider to climb on. It is a small area and small children tend to populate that side of the park. But all kinds of community members are in the park every day, from very elderly people in wheelchairs, accompanied by nurses, soaking in the sun on nice days, to baby birthday parties, or open to all parties where everyone brings some food and drinks. Every year the park has a Halloween Parade that is especially for families with young children. The buildings in this area are well known for their Halloween spirit, both in their decorations and the size of their candy.

At any time of year the park is a great place to walk your dog or watch other people walk there dogs. After dark, some dog owners let their pets off their leashes. There are very good restaurants in the area, many with outdoor seating, and at least one with direct views of the park. Signposts in the area point to many historic houses and community buildings.

https://www.nycgovparks.org/parks/cobble-hill-park/history

http://cobblehill.nyc/wp-content/uploads/2023/01/Cobble-Hill-Association-State-of-the-
Organization-2022.pdf

https://untappedcities.com/2015/04/06/historic-verandah-place-and-cobble-hill-park-19th-century-mews-20th-century-views/

http://cobblehill.nyc/knowledge_base/cobble_hill_history/

https://www.brownstoner.com/services/outside-nyc-agents/d54528a2e8bb1c/cobble-hill-park-clinton-street-brooklyn-ny-11201/