---
author: "Warren Marburg"
title: "Fort Greene Park"
---

Between the Brooklyn neighborhoods of Downtown and Clinton Hill there lies a 30-acre park with over 150 years of history. It is often overshadowed by Prospect Park or Central Park, even though it holds just as much historical importance. Its significance traces all the way back to the revolutionary war, when it was used by the continental army as a fort for its high ground. It was later reused as a fort during the war of 1812. After the war, locals used the area primarily for recreation. The architects of Central Park and Prospect Park, Frederick Law Olmsted and Calvert Vaux, were hired in 1867 to design what was then called Washington Park. Later in 1897, the park was renamed Fort Greene Park. It was designed around its natural landscape, which made use of its hill features. It was Brooklyn’s first official park.

In the early 1900s, a monument for those who fought and died on British prison ships was erected. It stands at 150 feet tall at the highest point of the park. Arguably the most stand out feature of the park, the Prison Ship Martyrs’s Monument sits at the top of a climb of stairs and is visible from afar. It is a tall pillar that can encourage a trip to the top so one can see the entire monument up close. It could even be considered one of the seven wonders of New York. Other useful features have been added to Fort Greene Park, of which includes tennis courts, basketball courts, a visitor center and a butterfly garden.

The wide space of the park makes Fort Greene an optimal place for events such as festivals and concerts. One such festival occurs annually called the Fort Greene Park Summer Literary Festival. This event spotlights young writers from ages 7-18 and established writers from surrounding communities of the park and abroad. On the service side of things, the Fort Greene Park conservancy holds yearly cleanup projects during the summer.

In the past few years, renovation plans have been in the making. The city’s Parks Without Borders initiative held online surveys that allowed for nominations for parks needing renovations, of which Fort Greene was submitted. This initiated a proposition to transform the historic park. Accessibility is a key component of this plan, as is evident in the form of turning the stairs on Myrtle Street into an ADA ramp. Improvements to facilities, like an expansion of the adult fitness area, are also planned. The project will cost $24 million.

The plans for renovations have received much public opposition from the community. The advocacy group Friends of Fort Greene rose from this backlash. Criticisms of the plan being a “facade” for gentrifiers rather than an improvement for locals have been made. Another issue residents had with the renovation plan was that it would cut down rows of trees to make space for a promenade. The retaliation caused the Parks department to go ahead with construction while preserving the trees. Preservationists have also spoken up against the plan as they believe it would destroy the historic design of Fort Greene Park.

Sources:

[Brooklyn's Fort Greene Park is getting a major facelift](https://www.timeout.com/newyork/news/brooklyns-fort-greene-park-is-getting-a-major-facelift-041321#:~:text=NYC%20Parks%20just%20released%20a,wheelchair%20access%20and%20new%20sidewalks.)

[Here's How the Parks Department Wants to Transform Fort Greene Park](https://www.brownstoner.com/architecture/fort-greene-park-plans-design-renderings/)

https://www.nycgovparks.org/parks/fort-greene-park/history

https://en.wikipedia.org/wiki/Fort_Greene_Park

https://www.localize.city/blog/fort-greene-park-150-years-of-history-and-recreation/

https://www.brooklynpaper.com/longtime-residents-dont-gentrify-fort-greene-park/