---
author: "Warren Marburg"
title: "Brooklyn Bridge"
date: "5/11/23"
---


As early as 1800, plans were conceptualized for a bridge connecting Brooklyn and Manhattan, which were separate cities at the time. Before this time, the cities’ only connection was by ferry. Ultimately, the design that turned into the Brooklyn Bridge was made by John Augustus Roebling in 1852. According to the plan, this would become the tallest suspension bridge in the world. John A. Roebling passed away after a tetanus infection in 1869, which left his son Washington Roebling to replace him as chief engineer. The leader of Tammany Hall, a powerful political organization in New York, William Tweed became involved with the construction of the bridge at this time. The New York Bridge Company, incorporated in 1867, was overseen by Tammany Hall. Washington Roebling’s wife, Emily Warren Roebling, also played a major role in the construction of the bridge. She understood advanced mathematics, and taught herself the technical issues so that she could assist with the Brooklyn Bridge’s construction.

The project didn’t go without criticism. Some people thought the bridge would be too expensive to build or even too difficult. To calm these fears, John Roebling held a “bridge party” in 1869, gathering engineers and congress members to discuss the project. He showed his record of other successful suspension bridges at this meeting. After John Roebling’s death, the project was beginning to be thought of as “cursed.” Tammany Hall controlling the bridge company may have also caused worry, as the organization was known for political corruption.

The construction work involved was very dangerous. It required digging sediment into an air-pressurized caisson. They needed to work in the water of the East River. The temperatures would rise to 80 degrees in the summer while the water was ice cold. This would mean that workers were often shirtless in the cold water because the temperatures were too high. Several fires broke out during the work on the caisson on the Manhattan side. One of those fires was named “The Great Blowout,” which caused significant damage caisson. “Caisson Disease,” also known as “the bends,” was developed by workers who entered the pressurized air and exited too fast. Washington Roebling, who worked in the caisson himself, developed this “disease” which was later found to be decompression sickness. Since this paralyzed him, his wife Emily helped him finish the project. She was crucial in this stage of construction, and was able to assume the duties of chief engineer when Washington couldn’t. Her contribution came at a time where higher education was not as accessible for women, so her brilliance and knowledge of math and engineering was a triumph.

The construction of the bridge took 14 years and cost 15 million dollars, which is $130 million today. On May 24 1883, the grand opening of what was called the New York and Brooklyn Bridge commenced. Thousands of people were present for the momentous event. In attendance was President Chester A. Arthur, New York Governor Grover Cleveland, and of course New York City’s Mayor Franklin Edison. More than 150,000 people walked across the bridge within the first 24 hours. This was made possible by a promenade above the roadway designed by John Augustus Roebling specifically for pedestrians. 

The legacy of the Brooklyn Bridge can be characterized in multiple ways. Unfortunately, at least 27 people died during construction with tragedy continuing beyond the opening. Accidents, homicides, and suicides have taken place, giving the bridge it’s “cursed” reputation. Another way to characterize it is by its record-breaking achievement of connecting two important places. It directly led to the consolidation of New York City in 1898, which conjoined Brooklyn and Manhattan, as well as the other boroughs known today. Another often overlooked aspect of the Brooklyn Bridge’s legacy is Emily Warren Roebling role, which may have inspired and paved the way for future female engineers. 

Sources:

[https://en.wikipedia.org/wiki/Brooklyn_Bridge](https://en.wikipedia.org/wiki/Brooklyn_Bridge)

[https://www.citysignal.com/the-history-of-the-brooklyn-bridge-and-its-dark-legacy/](https://www.citysignal.com/the-history-of-the-brooklyn-bridge-and-its-dark-legacy/)

[https://www.history.com/topics/landmarks/brooklyn-bridge](https://www.history.com/topics/landmarks/brooklyn-bridge)