---
author: "Warren Marburg"
title: "Friends of MTA: Brooklyn subway stations"
date: "5/11/23"
---

Common complaints of subway stations in NYC include broken elevators, slippery stairs, and a lack of trash cans. These issues often go unnoticed by the MTA (Metropolitan Transit Authority). Recently, a new program in Brooklyn has surfaced, focusing on improving communication and accountability with regard to MTA train stations. Council Member Lincoln Restler announced this program in early March 2023. Under the name “Friends of MTA Station Initiative,” Restler is searching for commuters to volunteer to meet in groups with MTA officials. This is meant to encourage discussion between the MTA and riders. 

Jon Orcutt, a transit advocate and transportation policy expert, believes this initiative will promote accountability. This initiative will start with five participating stations in northern Brooklyn: Jay Street, Nassau Avenue, Borough Hall, Bedford Avenue, and High Street. Friends of MTA is similar to “Friends of” groups for parks, as well as other public spaces and institutions. Prospect Park Alliance was founded in 1987 after years of deterioration in the park. A project they took on recently had to do with safety on Prospect Park Drive. Prospect Park Drive closed to outside vehicular traffic in 2018, and has never fully been redesigned since. Prospect Park Alliance released a study to provide information on the injuries and incidents that have occurred on Prospect Park Drive since its closure, in an attempt to call attention to the need of a redesign.

Friends of MTA does not seek any donations, as it is mainly fueled by volunteers. Lincoln Restler aims at creating a ‘framework’ for accountability and station improvements that could make a “tangible difference” in the experiences of commuters. Newsbreak contributor Sara Irshad said that the initiative is “an excellent opportunity for New Yorkers to take an active role in improving the subway system.” The focus of Friends of MTA is on commuter involvement and communication with officials. 

MTA improvement advocacy existed long before the introduction of this initiative. Riders Alliance formed in 2012, and has become a prominent organization aiming at identifying issues in the wider MTA system, including busses. Riders Alliance is more of an advocating movement, while Friends of MTA is directly involved with officials. Another key difference is that Friends of MTA is focused on five subway stations instead of the entire system. A press release states, “Groups will meet with MTA and other agency officials to discuss station conditions, conduct walkthroughs, and learn more about what is currently done under MTA’s operating and capital budgets. The purpose of this engagement model is to provide the community with a better understanding of their stations and have a consistent line of communication with the MTA.” Communication is key in the functionality of this initiative. Although there hasn’t been word on it yet, the Friends of MTA program may extend to more stations in the future, or inspire similar programs.

## Sources

[https://bronx.news12.com/friends-of-mta-initiative-aims-to-improve-5-brooklyn-subway-stations](https://bronx.news12.com/friends-of-mta-initiative-aims-to-improve-5-brooklyn-subway-stations)

[https://www.brooklynpaper.com/restler-friends-of-mta-subway-stations/](https://www.brooklynpaper.com/restler-friends-of-mta-subway-stations/)

[https://gothamist.com/news/want-to-be-friends-with-a-subway-station-a-brooklyn-councilmember-seeks-volunteers](https://gothamist.com/news/want-to-be-friends-with-a-subway-station-a-brooklyn-councilmember-seeks-volunteers)

[https://original.newsbreak.com/@sara-irshad-1602721/2946993375458-improving-the-subway-brooklyn-councilman-launches-friends-of-mta-station-group](https://original.newsbreak.com/@sara-irshad-1602721/2946993375458-improving-the-subway-brooklyn-councilman-launches-friends-of-mta-station-group)

[https://www.cityandstateny.com/opinion/2023/03/editors-note-friends-mta-are-welcome-support-new-yorks-subways/383921/](https://www.cityandstateny.com/opinion/2023/03/editors-note-friends-mta-are-welcome-support-new-yorks-subways/383921/)

[https://www.prospectpark.org/learn-more/what-we-do/](https://www.prospectpark.org/learn-more/what-we-do/)

[https://www.ridersalliance.org/our-story](https://www.ridersalliance.org/our-story)