---
author: "Nicole Roytlender"
title: "Coney Island Boardwalk"
---

Any long-term Brooklyn resident, or even NYC resident most likely remembers a childhood, summer experience at Coney Island. Food, rides, carnival games, and side shows are just some of many attractions the area has to offer. Coney Island has a long history even prior to the establishment of Luna Park in 1903, however the amusement park undoubtedly increased attention. In 1920, the reputation reached new heights as Coney Island became accessible by the subway making it known as the “Nickel Empire” as it cost a nickel to get there, a nickel for the rides, and a nickel for the famous hotdogs. Succeeding the Great Depression, however, the park was largely torn down with a few of the original rides remaining, namely the Cyclone. anti-commercialization efforts impeded the rebuilding process, however, the park Is definitely back in business present day. “While the overall image is unrefined, somewhat disorganized, and a little dirty, and it cannot be considered a peaceful or relaxing place to be in any traditional sense, these informal qualities are all part of its attraction. Much of the image of Coney Island is imbedded in its history” (Coney Island: Waterfronts). Renovations are still ongoing as some question the safety of the boardwalk itself and other infrastructure components, but with those being squared away the area is constantly flooded with locals and visitors in the warmer months. People who live nearby take evening strolls along the boardwalk when the weather permits.  Many events take place on and near the boardwalk as well such as the Nathan's hotdog eating contest every Fourth of July. Additionally, there is the Mermaid Parade that has been drawing in crowds since 1983. To add, baseball games are not hard to come by near the boardwalk as the home stadium of the Brooklyn Cyclones is right by the pier. The Cyclones being the first Brooklyn team since the Dodgers left for LA, brought back a sense of community for the sports fans of the area. Tickets for the games are generally affordable and always draw in crowds of all ages. The boardwalk is frequently lined with people playing music either for themselves or for crowds. On especially nice summer nights you can even catch people dancing on the pier at the end of the boardwalk. There are also many vendors selling souvenirs, fruit, and more available for purchase.  Many long-standing restaurants create points of interest along the boardwalk as well including the aforementioned Nathan's Hot Dogs, Totonno's Pizzeria Napolitano, Gargiulos Coney Island, and more. Many of these establishments have history dating back over 100 years. This all goes to show how rich the area is with culture and history. Families of all backgrounds can be found enjoying summer days and nights on the boardwalk in Coney Island. 

Sources: 

“Coney Island: Waterfronts.” *Home - Project for Public Spaces*, www.pps.org/places/coney-island. Accessed 23 May 2023.

Caputo, Paul. “What a Ride: The Story behind the Brooklyn Cyclones.” *SportsLogos.Net News*, 5 July 2015, news.sportslogos.net/2015/07/04/what-a-ride-the-story-behind-the-brooklyn-cyclones/baseball/.