---
author: "Nicole Roytlender"
title: "Nellie Bly Amusement Park "
---

Nellie Bly Amusement Park 

Luna Park's smaller counterpart, intended for younger children (ages 3-6), was formerly known as Nellie Bly Amusement Park. Now known as Adventurer's Park, the attraction was originally named after Nellie Bly, an American journalist and inventor who famously completed a world-round trip in a short 72 days. Elizabeth Jane Cochrane wrote under the pen name “Nellie Bly” when she began writing for the *Dispatch.* Her writing was heavily focused on women, as pertaining to jobs and factory life, as well as marriage and lifestyle choices. After her progressive writing style received critiques from higher-ups, she was forced into writing journalism pieces about “typical” feminine subjects such as fashion, gardening, home-making, cooking and matters of the like. Growing discontent with her repressed writing freedom, she ventured to Mexico for six months and wrote about the oppressive rule of Porfirio Diaz. She did so until unsafe circumstances led her to flee back to the States. After unsuccessful months spent back home, she finally made a breakthrough by going undercover into a woman's insane asylum in an attempt to broadcast the deplorable and abusive conditions patients were subjected to. This piece earned her significant recognition and public appreciation. Later, she decided to take on the world-round trip that would become the theme of Nellie Bly Amusement Park, “Around the World in Eighty Days.” “The concessionaire named the fun park for Nellie Bly because of her reputation as an adventurer. The park features more than a dozen kiddie rides, including a miniature roller coaster, ferris wheel, carousel, and train. Although most of its amusements appeal to younger children, Nellie Bly also sports an 18-hole miniature golf course, batting cages, and go-carts”(*Nellie Bly Park Highlights : NYC Parks).* The Park does not typically face over-overcrowding as the location is fairly secluded unlike Luna Park making it appealing to families with younger children. Nonetheless, it is a short walk from Ceasar's Bay Bazaar, which offers food and shopping options that are not prominent in the park itself. Not really known as a tourist attraction, Nellie Bly is more frequently known to locals of all ages who grew up in Bensonhurst since the park first opened its gates in 1966. Seasonal events take place here as well during the summer and into Halloween time. Despite the fairly recent renaming, the park's historic significance and representation of an important New York journalist has not diminished. Many people still regard the park by its original name and continue to bring new generations of youngsters. 

Sources: 

Frishberg, Hannah. “Remembering Nellie Bly, Bensonhurst’s Ever-Evolving Kiddie Theme Park.” *Bklyner*, 27 Sept. 2016, bklyner.com/37785-bensonhurst/.

*Nellie Bly Park Highlights : NYC Parks*, www.nycgovparks.org/parks/nellie-bly-park/history. Accessed 24 May 2023.