---
author: "Nicole Roytlender"
title: "Coney Island Public Beach"
---

New York City is known for many things, however nice, sandy beaches are not typically on the top of that list. Nonetheless, locals can be spotted making use of the few beaches we do have access to as soon as the warm weather hits. Despite this, pollution is not a foreign concept for the City, which unfortunately extends to the beaches. In particularly, Coney Island Beach in Brooklyn is regarded as one of the least cleanly. “Water quality has been a long-standing issue at Coney Island. The beach has been closed due to high levels of bacteria in the water on multiple occasions” (WalletGenius). The area itself generates a great deal of foot traffic, due to the boardwalk and attractions nearby causing crowding and pollution by visitors. There are also many businesses along the water, which inevitably contribute to the pollution. “When storm water hits the streets, it rolls along the street, and it picks up everything in its path… And you can imagine in New York City, the amount of city grit and grime that it’s picking up along with human and animal waste, along with oil that’s on the ground, being picked up with the storm water and carried into the ocean”(Dyer). Not too far away, Brighton Beach, is regarded as less contaminated, however the closer the beach extends to W 8th St. and the pier, the higher the levels of bacteria become. Additionally, during the pandemic, the trash situation seemed to only get worse as employees were not tending to the surrounding area due to closures. There are local cleaning initiatives in place in an attempt to restore and upkeep cleanliness as locals are noticing the heightened dirt and waste in the area and expressing concerns. To add, there is an aquarium located on the beach front that participates in beach clean-ups and invites people to join in attempt to promote Ocean conservation. It is important that said initiatives are further promoted and created as Brooklyn residents rely on beaches and pertaining amenities in the summer months to escape the hustle and bustle of City life. Many are not able to afford the time-off or expense of tropical luxurious beach vacations and Coney Island beach serves as the next best thing for many, being just a short car or train ride away. Children and young adults are also given a place to go when off from school to find a source of relaxation while parents are busy or at work without having to travel out of the neighborhood. There are volleyball nets on the beach and structures of the like that allow for recreation and being able to take a dip in the water after participating in said activities should be a part of the experience no-one worries about. Overall, bringing awareness of residents and local government to the maintenance of Coney Island Beach should be a priority as neglecting it will only lead it down a further path of contamination until eventually its use will be a thing of the past.    

Sources:

“Worst Beaches in America in 2023.” *WalletGenius*, 14 Apr. 2023, walletgenius.com/travel/worst-beaches-in-america-in-2023/. Accessed 16 May 2023.

McGovern, Gabrielle. “Report: Coney Island Listed as One of NYC’s Most Contaminated Beaches.” *WFUV*, wfuv.org/content/report-coney-island-listed-one-nycs-most-contaminated-beaches. Accessed 16 May 2023.

**Beach Concerns:** 

[https://walletgenius.com/travel/worst-beaches-in-america-in-2023/](https://walletgenius.com/travel/worst-beaches-in-america-in-2023/)

“Coney Island, located in Brooklyn, New York, is a historic beach and amusement park that has been entertaining visitors for over a century. However, the beach has also earned a reputation as one of the worst beaches in the country due to a number of issues, including aging infrastructure and poor water quality.

One of the main concerns facing Coney Island is the aging infrastructure. The beach’s boardwalk and facilities are in need of repair and renovation. Additionally, water quality has been a long-standing issue at Coney Island. The beach has been closed due to high levels of [bacteria](https://wfuv.org/content/report-coney-island-listed-one-nycs-most-contaminated-beaches) in the water on multiple occasions. Efforts have been made to improve water quality, but the issue remains a concern for visitors to the beach”

[https://bklyner.com/coney-island-beach-water-quality-sheepshead-bay/](https://bklyner.com/coney-island-beach-water-quality-sheepshead-bay/)

**History:** 

[https://www.pps.org/places/coney-island](https://www.pps.org/places/coney-island)

History of Coney Island