---
author: "Nicole Roytlender"
title: "Ceasar's Bay Bazaar"
---

Ceasar's Bay in Bensonhurst, Brooklyn has evolved over the years. Now the area is a large shopping center with many big box stores such as Target, Kohls, Best Buy, 5 below and more. Originally it began as a Korvettes department store and later changed identity in 1982 when Ceasar Salama and Joseph Gindi “took the old E. J. Korvettes site on Bay Parkway and turned it into Ceasar’s Bay Bazaar.” (Salama). The Bazaar operated for fourteen years inviting 700 local vendors and craftsmen a place to sell goods at the waterfront location. Merchants peddled their goods giving purchasers unbeatable prices at this cross between a department store and a flea market. Eventually, a Kmart offered the owners a substantial figure of money convincing them to sell the location. Despite this, the name remains intact and the history not forgotten. Although many of the businesses directly following the Bazaar have come and gone, one business in particular has been standing since 1998 and that is Pizza D' Amore. It is unusual but relieving to see a small business operating amongst the heavily commercialized shopping center. Among shoppers, the area attracts individuals seeking waterfront serenity at the adjacent boardwalk/bike path. People take to this path for exercising purposes, fishing, or a mere calm place to sit and watch the sunset cast beautiful colors over the water. There is even a big rental pop-up operating in the warmer months that many families and individuals make use of. There is always a Carvel ice cream track at the beginning of the path with a swarm of children around and even adults waiting to get a sweet fix before embarking on a walk. Some worry that the new stores signify a sense of gentrification looming over the neighborhood as it risks taking away business from the nearby 86th Street, just a few blocks down Bay Parkway. Although this concern is genuine, the businesses on 86th Street have something to offer that Ceasar's Bay does not, which is culturally authentic food and shopping centers. To add, there is a surge of many new small restaurants and stores on the street since the pandemic showing that Ceasar's Bay is not causing the business there to suffer. Bensonhurst is a primarily working class area and many of the residents benefit from affordable department stores in the neighborhood alongside the traditional, cultural businesses. To add, the stores bring about many entry level positions to be filled by locals, which debatably can be a good factor but not everyone may agree. What is undoubtable is the history behind Ceasar's Bay Bazaar and the amount of people that make use of it daily.  

Sources: 

Rosalie Radomsky. If You’re Thinking of Living in Bensonhurst. 26 Aug. 1984, [https://www.nytimes.com/1984/08/26/realestate/if-you-re-thinking-of-living-in-bensonhurst.html](https://www.nytimes.com/1984/08/26/realestate/if-you-re-thinking-of-living-in-bensonhurst.html).

Henry. *Was There Ever Really a “Ceasar’s Bay”?* 8 Aug. 2016, [https://www.heyridge.com/2016/08/was-there-ever-really-a-ceasars-bay/](https://www.heyridge.com/2016/08/was-there-ever-really-a-ceasars-bay/).