---
author: "Saadiya Taylor"
title: "Prospect Park"
---

Proclaimed to be “the heart of Brooklyn”, Prospect Park’s creation was influenced by the success of Manhattan’s Central Park. As Brooklyn was the third largest city, it was encouraged by the state and Brooklyn commissioners that a park was a necessity and desire for Brooklyn residents. Commissioners asserted that the construction of the park would have a positive impact on “upgrading the caliber of residences and the tax base of Brooklyn”. As a result, Frederick Law Olmstead and Calvert Vaux were assigned as park designers from 1860-1880. Olmstead used accurate topographic maps of the area to: move earth masses, form alley bridges and roads, and create careful drainage. In addition, he removed existing plants for new shrubbery imported from Europe and gathered inspiration from the Adirondack Mountain landscape to construct the Ravine which was considered the heart of the park. Also incorporating Concert Grove which was created to be an auditorium for summer outdoor concerts which were popular during the time.

Although Olmstead thoroughly designed the formation of Prospect Park, there are multiple contributing factors that led to its deterioration. The neglect of Prospect Park was a result of Brooklyn becoming a New York City district, the long-term activity of Robert Moses, and the park’s size. Brooklyn’s transition from an independent city to a New York City district caused the disregarding of Prospect Park as the issues of Brooklyn were considered secondary to those of Manhattan. Due to Manhattan being the borough that housed various influential people, most wealthy sponsors became private sponsors for Central Park instead of Prospect Park. 

Another reason is the lack of care for the original formatting when redesigned by Robert Moses. In 1930, Robert Moses was made NYC parks commissioner. During this time, he added improved sports facilities to all the parks under his supervision. The creation of soccer fields, skating rinks, and other sports facilities created recreational spaces for residents; however, the incorporation of these spaces destroyed the original design. Original spaces from Olmstead’s design like Concert Grove were altered with the incorporation of an ice skating rink and a portion of Long Meadow being converted into a soccer field. Moses altered the artificial landscapes designed by Olmstead which were covered by wild growth and unwanted plants and the bridges into homeless shelters. The redesigning of Moses along with natural forces and time caused the destruction of Music Island, removing it from the surface of the lake. 

Lastly, the size of the park was a contributing factor. Prospect Park is 526 acres, due to this, it is difficult to secure the entire premises. The lack of supervision and security made the park a ground for homeless people to find shelter without disruption from the police as they only entered when crimes were being committed. Despite the neglect and deterioration of Prospect Park, the efforts by ecological reservationists and park commissioners allow for the park to be the place it once was.

## Citations

“A Comeback for Prospect Park - Document - Gale Academic OneFile.” Accessed March 13, 2023. [https://go.gale.com/ps/i.do?p=AONE&u=cuny_broo39667&v=2.1&it=r&id=GALE%7CA17633318&inPS=true&linkSource=interlink&sid=bookmark-AONE](https://go.gale.com/ps/i.do?p=AONE&u=cuny_broo39667&v=2.1&it=r&id=GALE%7CA17633318&inPS=true&linkSource=interlink&sid=bookmark-AONE).

Crompton, John L. “A Review of the Economic Data Emanating from the Development of Central Park and Its Influence on the Construction of Early Urban Parks in the United States.” *Journal of Planning History* 20, no. 2 (May 1, 2021): 134–56. [https://doi.org/10.1177/1538513220971005](https://doi.org/10.1177/1538513220971005).

DiCicco, Jessica M. “Long-Term Urban Park Ecological Restoration: A Case Study of Prospect Park, Brooklyn, New York.” *Ecological Restoration* 32, no. 3 (2014): 314–26. [https://doi.org/10.3368/er.32.3.314](https://doi.org/10.3368/er.32.3.314).

Wilczkiewicz, Małgorzata Z. “LeFrak Center in Prospect Park (Brooklyn, New York) as an Example of Addition onto a Historical Landmark,” n.d.