---
author: "Abigail Tenenbaum"
title: "Brooklyn Public Library"
date: "5/12/23"
---

In 1896, the New York State Assembly and Brooklyn Common Council agreed to establish the Brooklyn Public Library. Prior to the library system’s creation, Brooklyn had a number of independently served libraries that were open to the public. Most, however, weren’t free, and required some kind of membership fee. The establishment of the Brooklyn Public Library system meant free widespread access for all. In 1897, the Bedford Library is the first location to open within the Brooklyn Public Library system. Throughout the 20th century, locations spanning all over Brooklyn would be built, including 21 locations that Andrew Carnegie donated $1.6 million for. 

The Brooklyn Public Library is one of the largest public library systems in the nation, serving Brooklyn’s 2.7 million population across 61 different branches throughout the borough. Besides the branches themselves, there are also outreach sites in various locations such as schools and senior centers. The Brooklyn Public Library offers a multitude of services, from work development programs to cultural enrichment events to after-school educational programs. The Brooklyn Public Library system has been commended for its role in serving the Brooklyn population. The American Library Association’s 2014 Public Library Data Service Statistical Report ranked Brooklyn Public Library 3rd in the nation for its public programs and program attendance. Additionally, in 2016, the Brooklyn Public Library was rewarded an IMLS National Medal for Museum and Library Service due to the Outreach Service’s department’s efforts in aiding Brooklyn’s vulnerable populations. 

The Brooklyn Public Library has also been at the forefront in fighting nationwide book banning efforts. In the past couple years, book banning efforts have surged throughout the United States.  In 2021, the American Library Association (ALA) counted 729 challenges targeting 1,579 books. Between July 1, 2021, and June 30, 2022, bans occurred in 138 school districts over 32 states. Of these books, 41% explicitly address LGBTQ+ topics, and 40% contain protagonists or prominent secondary characters of color. School districts and libraries are banning books by the dozen, particularly due to pressure from conservative organizations and furious parents. They push against books regarding topics of race, sexuality, and gender. This has led to the harassment of librarians and adults showing up armed to library board meetings, as well as successful attempts in banning books all over the country. 

“Books Unbanned” is a Brooklyn Public Library program that allows teenagers in the US, regardless of state, to get a library card with the BPL system. With the digital library card, teenagers in states with book banning policies are able to maneuver around the restrictions and use the vast digital library that Brooklyn has to offer. Over 6,000 teenagers have created accounts since spring 2022, free to read without consequence. The Brooklyn Public Library also created the Intellectual Freedom Teen Council, where teens from all over the US can connect via a peer-support network, discussing topics such as censorship and intellectual freedom. With the tremendous efforts that the Brooklyn Public Library pours into supporting those that face banned books, it certainly lives up to its reputation of helping those who need it. 

Friedman, PhD, Jonathan, and Nadine Farid Johnson. “Banned in the USA: The Growing Movement to Censor Books in Schools.” PEN America 100, September 19, 2022. [https://pen.org/report/banned-usa-growing-movement-to-censor-books-in-schools/](https://pen.org/report/banned-usa-growing-movement-to-censor-books-in-schools/).

Italie, Hillel. “Book Ban Efforts Surging in 2022, Library Association Says.” *AP News*, September 16, 2022. [https://apnews.com/article/libraries-american-library-association-book-banning-af7c9f312266b572c3dc189b1d109de4](https://apnews.com/article/libraries-american-library-association-book-banning-af7c9f312266b572c3dc189b1d109de4).

Social Networks and Archival Context. “Brooklyn Athenaeum,” n.d. [https://snaccooperative.org/view/56500741](https://snaccooperative.org/view/56500741).

Barron, James. “Brooklyn Library’s ‘Books Unbanned’ Team Wins Accolade.” *New York Times*, January 4, 2023. [https://www.nytimes.com/2023/01/04/nyregion/brooklyn-public-library-books-unbanned.html](https://www.nytimes.com/2023/01/04/nyregion/brooklyn-public-library-books-unbanned.html).

“Brooklyn Public Library,” n.d. [https://www.bklynlibrary.org/about](https://www.bklynlibrary.org/about).

“Why Book Burning Is Back.” *YouTube*, uploaded by Wisecrack, 24 October, 2022. [https://youtu.be/MYnpMx12S6Q](https://youtu.be/MYnpMx12S6Q).
