---
title: "Barclay Center"
author: "Kyi Williams"
---


The Barclay Center is a multi-purpose indoor arena located in Brooklyn, New York, that opened its doors in September 2012. Since then, the arena has become one of the premier entertainment venues in the country, hosting a variety of events from sports games to concerts to comedy shows. The center has a seating capacity of around 19,000 for basketball games and up to 20,000 for concerts, making it a popular destination for fans of all sorts.

One of the most notable aspects of the Barclay Center is its design. The arena was designed by Ellerbe Becket. The result is a sleek, modern structure that features a unique exterior made up of thousands of weathered steel panels. Inside, the arena is just as impressive, with state-of-the-art technology and amenities that cater to both fans and performers alike.

The center is home to the Brooklyn Nets of the NBA, who relocated to Brooklyn from New Jersey in 2012. Since then, the team has become a fixture of the Barclay Center, drawing in fans from all over the city and beyond. The arena also hosts a variety of other sporting events throughout the year, from college basketball games to professional boxing matches. Another team that resides in the Barclay Center is the NHL team New York Islanders. The first NHL hockey game played at this venue was a preseason game between the Islanders and New Jersey Devils on 21st September 2013. In addition, the Barclays Center is known for the NBA Draft which is a selection process where people are being drafted for the NBA.

Originally the Barclays Center was supposed to be open by 2006. However, with so much opposition going against it at the time, this created a series of financial and legal complications for the New Jersey Nets owner Bruce Ratner. Because of this, Ratner began looking into selling his team. On September 23, 2009, Russian businessman Mikhail Prokhorov bought the Nets for $200 million.

While sports are a major draw for the Barclay Center, the arena is perhaps best known for its concerts. Over the years, the center has hosted some of the biggest names in music, from Beyoncé to Bruce Springsteen to Jay-Z. Adding on, Jay-Z a New York native has a small stake in the Brooklyn Nets. The arena's acoustics are top-notch, ensuring that every seat in the house is the best seat in the house. Fans can expect a truly unforgettable experience when they attend a concert at the Barclay Center.

Beyond sports and concerts, the Barclay Center also hosts a variety of other events, including comedy shows, family-friendly performances, and more. The arena's flexible layout and state-of-the-art technology make it a versatile space that can be transformed to suit any event. The Barclays Center is an accessible arena because it has access to 11 subways and the LIRR, including a couple buses.

Overall, the Barclay Center is a world-class entertainment destination that has something for everyone. Whether you're a sports fan, a music lover, or just looking for a fun night out, the center is sure to deliver. With its stunning design, top-notch amenities, and impressive roster of events, it's no wonder that the Barclay Center has become one of the most popular venues in the country.

“History Of Brooklyn’s The Barclays Center - ClassicNewYorkHistory.Com.” Accessed May 8, 2023. [https://classicnewyorkhistory.com/history-of-brooklyns-the-barclays-center/](https://classicnewyorkhistory.com/history-of-brooklyns-the-barclays-center/).

http://www.insidearenas.com/author/admin. “Barclays Center.” InsideArenas.com, April 28, 2023. [http://www.insidearenas.com/eastern/BarclaysCenter.htm](http://www.insidearenas.com/eastern/BarclaysCenter.htm).

“Barclays Center: History, Capacity, Events & Significance.” Accessed May 8, 2023. [https://sportsmatik.com/sports-corner/sports-venue/barclays-center](https://sportsmatik.com/sports-corner/sports-venue/barclays-center).

Pentagram. “Barclays Center — Story.” Accessed May 8, 2023. [https://www.pentagram.com/work/barclays-center/story](https://www.pentagram.com/work/barclays-center/story).