---
title: "Weekly Assignments"
author: "Matt Crump"
---

This page was created at the end of the semester. Weekly assignments were generally posted on Blackboard or the share notion workspace.

## Week 1: Introductions

Posted on Blackboard: 

This is a discussion board forum for our next class Monday, January 30th.

Your assignment is to read two sections of the textbook: "About the series" (1 page), and the introduction (20 pages). These sections explain the purpose, motivation and structure of the textbook. 

We are using this textbook as one method to learn about the people of NYC. We will also create our own version of a book like this for the semester long project. 

Keeping these issues in mind, we will have a group discussion about the reading in our next class

Discussion forum assignment:

1. Create a new thread in this forum, and:

2. In your thread write a question that could be used to guide our class discussion about the reading. The question can be about about the reading, and/or about how it relates to our class learning goals. When we have our class discussion, we will look at the questions in this forum and talk about them in person.

3. If someone else has already posted your question, you could give that one a bump, but please also make a new question so we have lots of them to discuss.

Example:

I will get us started by creating my own thread, and asking a question I had.

See you all on Monday!

## Week 2: The Bronx and Group Presentations

In preparation for week 2 you have read the textbook chapter on The Bronx. The class assignment for this week is to create and deliver a short 3 minute presentation about one of the sites in the chapter.

Monday, February 6th is a workshop day where you will work with your partner to prepare the presentation.

1. Choose a unique site of interest from the textbook to present

2. Plan out the presentation for Wednesday

3. Participate in class discussions about the goals for our presentations

See also the attached "Oral Presentation Tips" document that we will discuss in class. It has many good tips, and we will modify aspects of it for our purposes.
Wednesday is presentation day or practice talk day. Each pair will deliver their 3 minute presentation followed by questions from the group.

Use this assignment to submit the powerpoint, google slides, or other content that you want to present. The deadline is 2pm Wednesday 8th, 2023 (I need time to make sure everything works). Bring your laptop just in case.

NOTE: only one person needs to upload the content for the pair, decide in advance who will be responsible for this step

These are the general guidelines for the presentations that I had on the projector during class:

General Guidelines

Time: 3 minutes, each partner gives half of the talk. 1.5 minutes per person (4.5 minutes for groups of 3).

Audience: Assume a general audience

Content: What are the points I want to convey? What do I want the audience to learn? When audience members remember my talk the following day, what main point do I want them to remember?

Organization:

- Introduce yourselves

- Introduce your site, establish the goal of your presentation

- Describe the site: Give no more than a one-minute summary of the site

- Feel free to go beyond the textbook description to help portray the site and its importance

- Site reflection/discussion: What issues are raised by this site? What are the broader contexts at play? What are the important takeaways from this example?

- Conclude with a summary of your main points.

## Week 3: Notion and note-taking

Note: a notion.so workspace was created and each student was invited to join. From this point forward most assignments were completed on notion pages. 

Your assignment is to engage the reading with a note-taking process using notion. This is an open-ended and unstructured assignment where you get to define and explore your own note-taking process. Whatever you decide to do, it should help you engage more deeply with the reading (e.g., help you remember important details, attempt to synthesize information by jotting ideas down, generating questions, critically evaluating ideas, locating other source material, etc.)

When you join the class notion you will find your own page in the list of member pages. Use this page to add your notes about the Manhattan reading. You can structure them however you want. You can add subpages and subpages of notes within your own member page.

This is a shared space so you will be able to see what everyone else does. We can even add comments to each other. As we are learning this system please do not delete content in a member page that is not your own.
To get full points for this assignment I expect your notion page will be full of your notes by our next class. In that class we will discuss the reading, your note-taking processes, and how we can use notion as a collaborative space to create content about our class.
Submission instructions

If you successfully join notion and add your note-taking process to your member page by the due date (next class), then you do not have to submit anything! I will automatically record your points for this assignment
If you had technical difficulties with notion that’s OK, however, I expect you will find another note-taking method and submit evidence of your notes to this assignment. We can figure the notion issue later.

## Week 4

Theme for the week: “Ourselves and our own experiences”

Overview:

As we continue learning about the people of NYC, we will consider our own roles as individuals in NYC. One assignment is to make an “About me” bio page. Another assignment is to learn about a research method called “Autoethnography” that describes how a researcher may draw upon their own personal experiences as a part of their larger research process.

These are the reading and writing assignments.

Reading:

Autoethnography. Read the attached 12-page manuscript describing a research method termed “Autoethnography”.
Continue reading sites from the Manhattan chapter. A minimal goal is to have read and taken notes on at least half of the sites. Choose the ones that most interest you.

Ellis, C., Adams, T. E., & Bochner, A. P. (2011). Autoethnography: An Overview. Historical Social Research / Historische Sozialforschung, 36(4), 273–290.



Writing:

1. Autoethnography. Read the assigned paper and write a reflection about it in at least 500 words. Write your reflection in notion as a new page inside your member page. You can reflect on anything you want about this paper. If you had trouble understanding what this paper is about, discuss what questions you have. What do you think about this method? What are some limitations of the method, or exciting possibilities of the method? What aspects of the piece stood out to you as something for further reflection? 

Another possibility for your reflection paper is to write about your own experience as a person in NYC. What is it like to be you in NYC? What are you observing? Noticing? Feeling? What issues, concerns, interests and questions do you have from your own experience that relate to themes in this course, and could suggest research directions for topics you want to learn more about.

1.5 points. DUE BEFORE TUESDAY’s class. Submit by making a new page on notion.

Having done the reading and a reflection will allow you to participate in class discussion on Tuesday.

---

2.  About me. Share your bio/story with the class. Create an “About Me” subpage in your notion member page. Write a bio and introduce yourself, have fun with it. You can change this at anytime, and it will only be available to our class.

1 point. DUE BEFORE Wednesday’s class. Submit by making a new page on notion.

---

3. Manhattan notes. Continue adding notes about the sites you read from the Manhattan chapter. By Wednesday, you should have read and taken notes on at least half of the sites. Mix-up your note-taking process to try out different strategies. Demonstrate your agency.

1 point. DUE BEFORE Wednesday’s class. Submit by adding notes to your existing Manhattan notes.

If you have questions please email me, or ask them in the class help discussion board on notion.
-------------------------------------------

NEW END OF WEEK Self assessment

We are doing this in class, February 22nd. The instructions are to respond to these self assessment questions, and hand in your self assessment to this assignment. 

Did you do all of the reading and writing assignments by the deadlines?

If no, explain what happened. What is your plan to complete the reading and writing for this week?
How did you contribute to and/or participate in the class this week?

What are you goals for next week?

## Week 5: Oral History

This week we are learning about Queens and oral histories. There are three assignments.

**Oral History (1. 5 points, DUE BEFORE CLASS, Monday Feb 27th.)**

This week we learn about oral history methods. And, you get to choose what to read or listen to (for extra fun do both!)

Readings on Oral History:

- Ritchie, D. A. (2014). *Doing oral history: A practical guide*. Oxford University Press. (available as a digital ebook for free from BC library, read first chapter or as much as you want).

- Thomson, A. (2007). Four paradigm transformations in oral history. *The Oral History Review*, *34*(1), 49–70. (pdf on notion)

- Yow, V. (1997). “Do I like them too much?”: Effects of the oral history interview on the interviewer and vice-versa. *The Oral History Review*, *24*(1), 55–79. (pdf on notion)

Listen to oral histories about Queen’s from the Queen’s memory project, they have lots of podcasts to listen to:

<https://queensmemory.org/>

<https://queensmemory.org/podcast/>

Instructions for Assignment: Write…Or speak…

In at least 300-500 words (write them or record yourself speaking them.) It is very important to complete this assignment before Monday’s class. We will be doing some peer-review on each others work, so be prepared to share.

1. Discuss what you already knew (or prior perspective) about your chosen reading/ oral history / podcast.
2. Discuss what you learned and what was new for you about what you read and/or listened to
3. Discuss what you want to learn more about in relation to the reading/listening, and in relation to this class.

**Queen’s Reading and Notes (1 point, DUE Wednesday, March 1)**

1. Read the chapter on Queen’s (it’s much shorter at 33 pages)
2. Make a Queen’s page in your notion, and contribute notes as learn about different sites in Queen’s.

**Possible Sites Page (1 point, Do this ASAP, it's easy, then add to it)**

1. Make a “Possible Sites” in your notion
2. Use this space to add possible topics for the final project. Listing them here as they pop into your head will be helpful later.
3. Put at least one or two possibilities in here.

## Week 6: Octalogs

This week we begin the Brooklyn chapter and consider methods from history, the rhetoric of historiography
The additional reading presents numerous viewpoints about historical research, in four papers called the Octalogs.
The first octalog was in 1988. It occurred at a Conference on College Composition and Communication (CCCC) conference. Eight (octa) panelists at this conference had a few minutes to state their perspective about what historiography is all about. Octalog II happened 12 years later (1997), then Octalog III (2011), and the most recent Octalog IV was disrupted by COVID-19 in 2020, and took place in 2021. Collectively, these vignettes show both a wide range of viewpoints about history and historical research, as well as how those viewpoints have changed within the discipline over the past several decades.

NOTE: each of the octalogs are on notion under the week 6 assignment

Assignment

Octalog reading (Due Monday, March 6, 2023: 2.5 points)
There are four readings.

Read at least one speaker’s perspective from each of the readings. One from 1988, one from 1997, one from 2011, and one from 2021

For each perspective, in 100-200 words, briefly describe the major points the author is making

In 100-200 words, reflect on the themes raised across the octalogs.

Textbook reading (Due Wednesday, March 8: 1 point): Read half of the Brooklyn Chapter. Make a new Brooklyn page in your notion. Contribute notes from the sites. Pay special attention to topics, peoples, sites, questions, that you want to learn more about.

Sources:

Agnew, L., Gries, L., Stuckey, Z., Tolar Burton, V., Dolmage, J., Enoch, J., Jackson, R. L., Mao, L., Powell, M., Walzer, A. E., Cintron, R., & Vitanza, V. (2011). Octalog III: The Politics of Historiography in 2010. Rhetoric Review, 30(2), 109–134. https://doi.org/10.1080/07350198.2011.551497

Enos, R. L., Atwill, J. M., Ferreira‐Buckley, L., Glenn, C., Lauer, J., Mountford, R., Neel, J., Schiappa, E., Welch, K. E., & Miller, T. P. (1997). Octalog II: The (continuing) politics of historiography (Dedicated to the memory of James A. Berlin). Rhetoric Review, 16(1), 22–44. https://doi.org/10.1080/07350199709389078

Hurley, E. V. (2021). Octalog IV: The Politics of Rhetorical Studies in 2021. Rhetoric Review, 40(4), 321–348. https://doi.org/10.1080/07350198.2021.1981108

Octalog. (1988). The Politics of Historiography. Rhetoric Review, 7(1), 5–49.

## Week 7: Brooklyn and Archival Research

Textbook reading and notes (Due Wednesday, March 15: 1 point):

Read the remaining half of the Brooklyn Chapter. Contribute notes from the sites. Pay special attention to topics, peoples, sites, questions, that you want to learn more about.

Research a topic (Due Monday, March 13: 2.5 points):

1. Make sure you have access to the shared Zotero library (see Zotero page)

2. Identify a Brooklyn topic to learn more about. You can choose one that is mentioned in the textbook. It can be about a person, place, site, process, you get to choose.

3. Find at least five sources that can help you understand your topic. Example sources are:

- academic articles
- books
- websites
- newspaper articles
- blogs
- oral histories
- original source material (letters, archive documents, etc.)

4. Create entries for each source in the shared Zotero Folder, inside the subcollection with your name on it

5. Use Zotero to generate a bibliography for your sources

6. Make a notion page for your topic

- Copy in the bibliography

- Briefly discuss each source that you have chosen. What is it about? What did you learn, or hope to learn from this source?

- In 100 words, reflect on your research process. What was your reason for choosing this topic? How did the research process go? What new questions do you have? Did you run into roadblocks? What next steps would you take to learn more about this topic?

## Week 8: Staten Island

Read the chapter on Staten Island and take notes (3.5 points)

Your assignment for this week is to read the chapter on Staten Island, and add notes about each site to notion. (3.5 points)

There are no additional readings or assignments. Use the extra time to catch up on any missing assignments, and/or to brainstorm possible sites for your final project.


## Week 9: Final Project Entry 1

In week 9 we are starting to write entries for the final project. This week's assignment is on a common theme, "Improvement Initiatives" in NYC. In class we brainstormed many issues for people in NYC that could use improvement. These could be historical or modern issues. We then spent some class time researching initiatives by people, groups, or organizations that are trying to improve something NYC. The record of class discussion and brainstorming is under the notion page for week 9.
For your assignment, you will be writing a textbook style entry about an improvement initiative of your choice, that is related to or impacts people in NYC today or historically. 

Your assignment this week is in two parts.
Part I Assignment instructions (1 point Due date Monday, March 27th)

1. Make a new notion page for the first final project entry

2. Choose an improvement initiative that will be the focus of your first entry

3. Conduct research to learn more about the improvement initiative

  - identify at least five sources
    
  - Put your sources in your Zotero folder
    
4. Produce notes about your sources

5. Produce a conceptual outline for your entry

Part II Assignment instructions (2.5 points Due date Wednesday, March 29)

1. Complete a first draft of your entry (500+) words.


## Weeks 10-14: Final project entries 2 to 5

Students conducted original research to write four remaining entries to the class final project. Each week involved writing workshops and independent student site visits to locations of interest for a given entry.

## Final self reflection:

Instead of a final exam, there will be a final self-assessment where you reflect on your engagement with the learning goals of this course. The information on this page is the same as the “Final self-reflection assignment” on blackboard.

Due: Wednesday, May 17th

5:30pm

Submit your self-reflection on blackboard.

Instructions:

This is a short exercise where you reflect on your engagement with this course, and assign yourself a grade. Please give each question a few minutes of your time. Submit your self-reflection to the “final self-reflection assignment” on blackboard.

**First half of the semester**

1. How did you engage with the course during the first half of the semester? Did you read all of the textbook chapters? Did you take notes on the textbook chapters? Did you read the additional reading and writing assignments? How did you contribute to class discussion? (Please discuss in at least 100 words)
2. In the first half of the semester, did you find other ways to engage with the course learning goals besides the formal class activities described above?
3. In the first half of the semester did you have any issues with time management? What are some strategies to manage these issues in the future?

**Second half of the semester (focus on the final project)**

3. Discuss how your choice of final project entries helped you engage with the learning goals for this course?

The learning goals for the course are available here [https://crumplab.com/peopleofnyc/](https://crumplab.com/peopleofnyc/)

This is also an opportunity to discuss more generally why you chose the entry topics that you did, and what you took away from the research and writing process? (at least 100 words)

4. One general course goal was to enrich your experience by visiting sites in the city such as neighborhoods, museums, and/or historical and cultural sites. After spring break we reserved class time on Wednesdays for site visits. Please describe one of your site visits and how it enriched your experience in general, and/or how it influenced the writing of one of your entries.

5. What letter grade should you get for this course? Please explain.

I am open to multiple explanations that can justify a grade, and I will consider your arguments. I provide some general guidelines below that can help you with your argument.

A+: All assignments completed almost always on schedule, lots of class participation, very strong attendance record. Highly excellent and commendable work across a variety of assignments, or exceptionally high quality work in a few assignments

A: Almost all assignments completed mostly on schedule, lots of class participation, very strong attendance record. Really solid and excellent work

A-: Most assignments completed, a good deal of class participation, strong attendance, really great work

B: Missed more than a few assignments across the semester, occasional class participation, medium attendance record

C: Missed several assignments, low class participation, low attendance record

F: Missed most assignments, low class participation, very low attendance record
















