---
title: "New-York Historical Society"
author: "Carina Alessandro"
---

The New-York Historical Society, located in the Upper West Side across from Central Park, is New York’s first museum. Founded with great self-awareness in 1804 by eleven men who wanted to preserve eyewitness evidence of the events of the American Revolution and British occupation of New York, the museum holds over sixty thousand works and artifacts as well as over 350 thousand books and three million manuscripts in its libraries. 

Its entrance has vaulted ceilings (similar to the one in the Grand Central Terminal Oyster Bar) and columns with interactive touch screens added during its 2011 $65 million renovations to make it less like a vault and more open to public learning. Inside, though, made more visible by such renovations (including making its theater bigger and adding a disability entrance, and exterior changes preservationists enjoy), contains many impressive holdings. These include George Washington’s bed in Valley Forge, the 1863 draft well that set off the Civil War riots, artifacts of activist an tennis player Billie Jean King, a gallery of a hundred Tiffany lamps, and the only surviving New York printing of the Declaration of Independence. Other  additions from the renovation include a Fredrick Douglas and Lincoln sculpture on each side of the building, as well as a clock that stopped when the second plane hit during 9/11 in its entrance. 

Though the NY Historical Society has impressive things inside like works of Thomas Cole, Rembrandt, and Audubon (all his Birds of America watercolor drafts), an interactive children’s history museum, and one of the oldest libraries in the nation thats also one of the twenty members of the Independent Libraries Research Foundation, it is important to acknowledge that its building was build by enslaved people. However, it ironically did house the first exhibition on the role of slavery in the city’s economy. The archived exhibition page from 2005 stated, “No place on earth has welcomed human enterprise more warmly. New York was also, paradoxically, the capital of American slavery for more than two centuries.” This is of course exemplified by the nature and history of the museum. Additionally, the society’s role as an independent institution was very important in 1994, as then it had been on the brink of disaster for many years and had almost signed away control of its library and some collection to New York University, which would have violated an agreement with trustees and elected officials to keep independence in exchange for public funding. At the time it was famous for its financial, real-estate, staff, and attendance problems that included closure of the galleries and the resignation of the chairman. However, it was lucky to bounce back due to the help of investments, grants, and fundraising. 

“About Us | New-York Historical Society.” *New-York Historical Society*, www.nyhistory.org/about. Accessed 16 May 2023.

Goldberger, Paul. “Is There Hope for Historical Society?” *The New York Times*, 11 Apr. 1994, www.nytimes.com/1994/04/11/arts/is-there-hope-for-historical-society.html.

“New-York Historical Society.” *The National Endowment for the Humanities*, www.neh.gov/divisions/research/fellowship/new-york-historical-society. Accessed 15 May 2023.

“New-York Historical Society: Venues.” *Constellation Culinary*, 8 Apr. 2022, constellationculinary.com/venues/new-york-historical-society/.

“NYC-Arts - The Complete Guide.” *NYC-Arts the Complete Guide*, www.nyc-arts.org/organizations/new-york-historical-society/. Accessed 16 May 2023.

Pasley, James. “15 American Landmarks That Were Built by Enslaved People.” *Business Insider*, 6 Sept. 2019, www.businessinsider.com/american-landmarks-that-were-built-by-slaves-2019-9#fraunces-tavern-in-new-york-7.

Pogrebin, Robin. “A Bunker of History Begins to Open.” *The New York Times*, 11 Apr. 2011, www.nytimes.com/2011/04/12/arts/design/new-york-historical-society-renovations-take-shape.html.

*Slavery in New York*, 2005, web.archive.org/web/20120430021212/www.slaveryinnewyork.org/about_exhibit.htm.
