---
title: "Earth Matter at Governors Island"
author: "Carina Alessandro"
---

Earth Matter NYC is an educational 501c3 nonprofit in Governors Island, an island in New York Harbor 800 yards from Lower Manhattan. (Governor’s Island is politically part of Manhattan, though it is geographically closer to Brooklyn.) Established in 2009, Earth Matter is a farm that focuses on circular use of resources as a NYC compost drop off site to reduce organic waste misdirected into landfills which would be used for other processes, such as making fertile soils, rather than causing more waste in transportation to far away sites and increasing methane emissions that exacerbate climate change. 

However, a significant function of Earth Matter is education, specifically encouraging community participation and leadership by engaging visitors and  volunteers and offering job training through internship and apprenticeship on environmental quality, protection, and beatification. This is achieved mostly though their Compost Learning Center where visitors often tour and see compost-making devices, methods, farm animals, decomposers, and pollinators, and experience the hands-on operation themselves— in addition to a monthly new workshop. 

Through the Compost Learning Center and other parts of the facility, Earth Matter composts yard waste and 28 thousand pounds/year of food/kitchen scraps from Governors Island as well as participating NYC community members such as the Fulton Stall Market. Also from Governors Island, they compost food vender service-ware as a part of their initiative for a Zero Waste Island in partnership with The Trust For Governors Island. Of this compost, 65 cubic yards were distributed to community gardens (in 2021). 

The aforementioned other parts of the facility include their Soil Start Farm which teaches gardeners to amend existing soil by using readily available materials to compost. They also have a relaxing lavender field where visitors/volunteers’ pruning gets turned into compost whose creation is financially supported by the sale of the lavender. There’s also the Soil Start Farm’s Heritage Bed Project, which dedicates nine soil beds to Black Southern, Chinese, European Jewish, First Nation, German, Italian, Japanese, LatinX, and Peruvian cultures; as well as their children’s gardening program called Compost Critters Club to promote sustainable habits in kids 2-4 and their caregivers; plus, their donation of produce to the Catholic Worker Soup Kitchen community; and lastly, their growth of local foods for Governors Island food venders.

All of these functions of Earth Matter are supported by the technological knowledge built by the growing large community of composters in NYC, and are done in such a way that also conserves to reduce combined sewer overflow, particular industrial wastewater that flood the sewer system. This is important as they’re managing and producing compost from over 500 thousand pounds of diverted organics per year. They’ve indeed gone through some trial and error, like trying different machines and changing them for different uses: for example, a wood chipper is good for breaking down yard waste but not compostable utensils. 

Back to the subject of education and job training, the apprentices and interns are more limited in quantity than the volunteers and visitors of course but are given knowledge enough to build their own compost facility or attract investment for them. On the other hand, volunteers do get to work the composting process, like mixing, aeration, adjusting carbon to nitrogen material ratio, etc. and even can even get eggs from the chickens (who eat food scraps and give manure in return) and a a free small bag of compost (which surprisingly smells nice, I can attest). Lastly, if  selected, one can even take a course to receive a certificate as a master composter. 

Works Cited

City Life Org. “Celebrate Earth Day 2023 on Governors Island.” *City Life Org*, 28 Mar. 2023, thecitylife.org/2023/03/28/celebrate-earth-day-2023-on-governors-island/.

“Earth Matter NY INC.” *GuideStar Profile*, www.guidestar.org/profile/27-0625845. Accessed 15 May 2023.

“Earth Matter NY.” *Fulton Stall Market*, fultonstallmarket.org/earth-matter-ny. Accessed 15 May 2023.

“Earth Matter.” *Earth Matter NY | The Art and Science of Composting*, 16 Apr. 2023, earthmatter.org/.

Miller, Rill Ann. “Composting, Zero Waste on NYC’s Governors Island.” *BioCycle*, 19 June 2020, www.biocycle.net/composting-zero-waste-on-nycs-governors-island/.
