---
author: "Vanessa Cruz"
title: "American Museum of Natural History"
---

The American Museum of Natural History, built by Albert Smith Bickmore, is located at 200 Central Park West, New York, NY 10024, and is noted as one of the world’s most preeminent scientific and cultural institutions. It was established in 1869 in New York City and has since been a major center of research and education in the natural sciences. The Natural History Museum has more than 30 million collections of research specimens and one of the largest collections of fossils and insects in the world. The museum has five different halls where you can see the extensive history and depictions of different animals and people. There are the Environmental Halls, Earth, and Space Halls, Fossil Halls, Animal Halls: Creatures from around the world, and Human and Culture Halls. Among these halls, visitors can see North American Forests, Dinosaur Bones, Reptiles and Amphibians, South American peoples, and information about the planets and stars. The museum conducts research in anthropology, astronomy, mammalogy, mineralogy, and vertebrate paleontology to name a few. The Hayden Planetarium is one of the world’s largest and has a 10,000-volume library on astronomy and a 75-foot diameter sky theater. The entire museum spans four city blocks and consists of 25 interconnected buildings. The museum has nearly five million visitors each year. One of the most enticing parts of the American Museum of Natural History is the Great Blue Whale. It is located in Milstein Hall of Ocean Life and is 94 feet long, weighing 21,000 pounds. It is said to be a reminder of what once was the great majesty of Blue Whales, as well as a reminder of the dangers of extinction.

Currently, the museum has a new exhibition that opened only last month. The Richard Gilder Center for Science, Education, and Innovation features an insectarium, and butterfly conservatory, and houses about four million scientific specimens. Plans for the exhibit were first announced in 2014 and the exhibit was planned to be 230,000 square feet. At the time, the new exhibit required $325 million to be built and City Hall had pledged $15 million towards its creation. If you were to visit the exhibit now, it would be a good idea to visit the insectarium! It has one of the world's largest displays of live leafcutter ants and a microscope station where visitors can observe pinned specimens of cockroaches, crickets, and ancient species that illustrate insects’ endurance over their 400-million-long existence on Earth. The insectarium also features a monumental model of a beehive which allows visitors to “enter” the hive and see honey bees at work on video displays, as well as a digital interactive called “Be a Bee” that demonstrates the roles different groups of honey bees play in the life of the hive.

“American Museum of Natural History.” Encyclopædia Britannica, April 26, 2023. https://www.britannica.com/topic/American-Museum-of-Natural-History.

American Museum of Natural history - NYC-arts. Accessed May 25, 2023. https://www.nyc-arts.org/organizations/american-museum-of-natural-history/.

Carltonaut. “American Museum of Natural History: The 5 Halls.” Carltonaut’s Travel Tips, January 21, 2021. https://carltonautstraveltips.com/2019/05/09/museum-natural-history-new-york/.

Kimmelman, Michael, and Peter Fisher. “Wonder and Awe in Natural History’s New Wing. Butterflies, Too.” The New York Times, April 25, 2023. https://www.nytimes.com/2023/04/25/arts/design/gilder-center-natural-history-museum.html.

“Mission Statement & History.” American Museum of Natural History. Accessed May 24, 2023. https://www.amnh.org/about.

Zeller, Jonathan. “Guide to the American Museum of Natural History.” NYCgo.com, November 4, 2019. https://www.nycgo.com/articles/guide-to-the-american-museum-of-natural-history/.