---
author: "Vanessa Cruz"
title: "Radio City Music Hall"
---

The “speakeasy belt” was a $ 91 million property in Midtown Manhattan owned by John D. Rockefeller in 1929. Rockefeller had a 24-year lease, and after the stock market crash of 1929, he made the bold choice to build an entire complex of buildings on the property with the intent of attracting commercial tenants. Samuel Roxy Rothafel, dubbed a theatrical genius, alongside John D. Rockefeller and the Radio Corporation of America came up with the idea of “Radio City,” a palace for the people, which it’s still regarded as today. Using the creative vision of Rothafel and the design expertise of Donald Desky, Radio City Music Hall was born. To make the building, Desky incorporated the use of marble and gold foil, Bakelite, permatex, aluminum, and cork.

Today, Radio City is one of the many art deco buildings in New York. It is considered “the showplace of the nation” and is the largest indoor theater in the world. The auditorium has an oval ceiling that curves down to the floor and reaches a height of 83 feet. The Great Stage is the length of a New York City block and is framed by a 60 feet-high and 100 feet wide proscenium arch. There are more than 6,000 seats and in the time that Radio City Music Hall has been open, it has received more than 300 million visitors.

Since 1933, more than 700 movies have opened there including The Lion King, To Kill a Mockingbird, Mary Poppins, and King Kong. Among the incredible architectural design and its triumphant birth, Radio City continues to attract people because of the popular entertainers who have performed there as well as the famous Rockettes. Amongst the many stars who have performed in the great theater are Frank Sinatra, Ella Fitzgerald, and Ray Charles. Radio City has also hosted the Grammy Awards, the Tony’s, and MTV Music Video awards, and is a continuous host for the popular talent show - America’s Got Talent.

The Radio City Christmas Spectacular is an annual tradition that has attracted visitors and New York Natives to the theater's halls for decades. The Radio City Rockettes first performed in 1933 and have been performing ever since. The 90-minute performance featuring the dancers consists of singing, humor, and precision dancing from over 140 performers. The show is family-friendly and is most definitely a must-see. The Christmas decorations all over the city mixed with the chance of snow make the Radio City Christmas Spectacular fun, unforgettable, and exciting to attend!

“Christmas Spectacular.” The Rockettes, April 28, 2023. https://www.rockettes.com/christmas/.

McLaughlin, Katherine. “There’s a Secret Apartment inside This Famous New York City Landmark.” Architectural Digest, November 30, 2022. https://www.architecturaldigest.com/gallery/radio-city-music-hall-you-facts.

“Radio City Music Hall Venue History.” Madison Square Garden. Accessed May 24, 2023. https://www.msg.com/radio-city-music-hall/history.
“Radio City Music Hall, New York |.” Responsible New York, January 3, 2023. https://www.responsiblenewyork.com/radio-city-music-hall/.

“Radio City Music Hall, New York.” , New York - Historic Theatre Photography. Accessed May 24, 2023. https://www.historictheatrephotos.com/Theatre/Radio-City-New-York.aspx.