---
title: "Central Park"
author: "Martina Garcia"
---

At the beginning of 1858 a park called Central Park situated in New York Manhattan was created. Central park is considered a world-famous public park, because the park addresses the recreational needs of the rapidly growing City. The main and original purpose of the park was to make the citizens that came from the countryside and that moved to New York feel closer to the countryside. Also, to incorporate nature so New Yorkers would have an escape from the city, buildings and suburbs. Over 150 years later, the Park still provides this essential purpose, and welcomes all visitors, while accommodating newer forms of recreational activities. Central Park is one of the most visited urban parks in the country and one of the most popular destinations in New York City.

You might ask yourself, who’s idea was to create Central Park and how did it happen? Well, In the 1800s, New Yorkers were highly influenced by the parks around the world and thus declared a competition for the designing of a recreation park. An existing village and farmland that was inhabited by Irish immigrants and African Americans, was chosen as the most apparent site for the landscaping. Something really fantastic about Central Park is that the park was the first public park in the United States. The two winners of the competition mentioned before were the British-American architect Calvert Vaux and Landscape architect Frederick Law Olmsted. Frederick Law came from Staten Island and got a pot of land. The park became accessible to all the citizens of New York, and not just the privileged. This public park would offer  families an attractive setting for carriage rides and provide working-class New Yorkers with a healthy alternative to the saloon. After three years of debate over the park site and cost, in 1853 the state legislature authorized the City of New York to use the power of eminent domain to acquire more than 700 acres of land in the center of Manhattan. An interesting fact about the construction of the park is that Central Park was one of nineteenth-century New York’s most massive public works projects. Some 20,000 workers–Yankee engineers, Irish laborers, German gardeners, and native-born stonecutters–reshaped the site’s topography to create the pastoral landscape.

Central park is not just a turistic, important landmark or  beautiful place to hang out with your friends and families but also a huge contribution to the community and environment of New York City. How does it help the environment and community? Well as you might know the Park’s trees not only decrease carbon dioxide levels, but also help cool the area during increasingly common heat waves that are exacerbated by the climate crisis. Metropolitan areas like New York City are often hotter than surrounding rural areas due to heat-absorbing materials like concrete and glass. Trees work as natural air conditioners, not only providing shade for the people sitting under them, but cooling the city as a whole. These trees also absorb water that evaporates in the heat, cooling the air temperatures around them.

Work Cited

*History of Central Park - Central Park*. [https://centralpark.org/history-of-central-park/](https://centralpark.org/history-of-central-park/). Accessed 5 May 2023.

“How Central Park Keeps New York City Healthy.” *Central Park Conservancy*, [https://www.centralparknyc.org/articles/park-city-healthy](https://www.centralparknyc.org/articles/park-city-healthy). Accessed 5 May 2023.

“Park History.” *Central Park Conservancy*, [https://www.centralparknyc.org/park-history](https://www.centralparknyc.org/park-history). Accessed 5 May 2023.

Foderaro, Lisa W. “The Parks That Made the Man Who Made Central Park.” *The New York Times*, 30 Oct. 2019. *NYTimes.com*, [https://www.nytimes.com/2019/10/30/travel/footsteps-frederick-law-olmsted-parks.html](https://www.nytimes.com/2019/10/30/travel/footsteps-frederick-law-olmsted-parks.html).

Khurana, Aishwarya. “The Sustainable and Cultural Significance of Central Park on New York.” *RTF | Rethinking The Future*, 18 Jan. 2021, [https://www.re-thinkingthefuture.com/2021/01/18/a2915-the-sustainable-and-cultural-significance-of-central-park-on-new-york/](https://www.re-thinkingthefuture.com/2021/01/18/a2915-the-sustainable-and-cultural-significance-of-central-park-on-new-york/).
