---
title: "The Vessel"
author: "Martina Garcia"
---

The vessel

The most remarkable feature of Hudson Yards is the curving stairway, which represents a new building. This interactive installation, which will allow visitors to explore a number of different perspectives on the town and its inhabitants, is designed by Heatherwick Studio in collaboration with Thomas Heatherwick. Vertical ascent offers an unbelievable view of the city, river and beyond in 154 intricate stair walks comprising 2,500 linear steps around and 80 landings. The vessel's got an English heritage here in New York City, which is just about everything else. It was created by an English architect named Thomas Heatherwick, whose various groundbreaking projects in London have transformed the city. In his own work, he combines the vision of creativity with realworld applicability. In fact, the Vessel is not actually The Vessel at this point in time. Until they can come up with something better, the Vessel is just a name that's been thrown around. The creators of the building hope that people are going to love it and name it after them. The Vessel, as it is now known, is an interactive art installation with a network of steps and landings, and visitors can walk or use an elevator to the top. Hollywood style. The Vessel story is a tale of how it's finished. The designer had done his best to conceal the design. So much that a barrier of 20 feet was built in northwest Italy to block public access to the steelworks from which the vessel's skeleton had been constructed. A part of it was taken to the U.S. in a tugboat on the Hudson river near New York City, heading for its construction site. The Vessel's been on pause a few times since its inception. The ship was shut down for social isolation as the outbreak of coronavirus reached its peak. Between 2019 and May 2021, around three people killed themselves by jumping off the vessel. By introducing security measures, the vessel was allowed to remain open to the public while not being destroyed. After all this, the workers have received training on how to recognize warning signals of someone considering harming themselves. The entries shall be entered in pairs or groups. Although there were more protections in place, a fourth suicide happened in July 2021. After this suicide the ship's been closed for a long time. Therefore, according to a lot of people, the barriers of the vessel ought to be raised or destroyed. At Hudson Yards, the Vessel is a center of attention. To finalize, If you would like to visit to get there, go to the 34th Street Hudson Yards station on a 7 train. Is really easy to find the vessel as soon as you get out of the train station. I am not really sure of the open hours, since from what I read the Vessel is closed. 

Work Cited

*How to Visit the Vessel: Photos, Tips, and FAQ’s – Earth Trekkers*. [https://www.earthtrekkers.com/how-to-visit-the-vessel-photos/](https://www.earthtrekkers.com/how-to-visit-the-vessel-photos/). Accessed 1 May 2023.

Nast, Condé. “The Vessel in Hudson Yards Has Finally Opened to the Public.” *Architectural Digest*, 15 Mar. 2019, [https://www.architecturaldigest.com/story/vessel-hudson-yards-opens-public](https://www.architecturaldigest.com/story/vessel-hudson-yards-opens-public).

Sierra, Lauren. “After Tragedy, How Does Hudson Yards Move Forward?” *The Click*, 17 Dec. 2021, [https://theclick.news/after-tragedy-how-does-hudson-yards-move-forward/](https://theclick.news/after-tragedy-how-does-hudson-yards-move-forward/).

Angne, Urmi. “10 Things You Did Not Know about Vessel, New York.” *RTF | Rethinking The Future*, 28 Jan. 2021, [https://www.re-thinkingthefuture.com/2021/01/28/a3030-10-things-you-did-not-know-about-vessel-new-york/](https://www.re-thinkingthefuture.com/2021/01/28/a3030-10-things-you-did-not-know-about-vessel-new-york/).

*Vessel | Hudson Yards*. [https://www.hudsonyardsnewyork.com/discover/vessel#](https://www.hudsonyardsnewyork.com/discover/vessel#). Accessed 1 May 2023.
