---
title: "Rockefeller Center"
author: "Martina Garcia"
---

The  period of huge economic growth was known as the Roaring Twenties this is when the Rockefeller Center stood in New York City's Lower Manhattan. It was on October 28, 1929, the day before the Wall Street crash that real estate developer John R. Todd hired architects to start building Rockefeller Center. L. The designers were Andrew Reinhard and Henry Hofmeister. In January 1930, these gentlemen proposed an initial design which they sadly had not agreed upon until 1932. As the population was not in a position to afford initial rental of some buildings, due to the financial depression. This development did not look like it would achieve any promising future under such depressing conditions for unemployment. However, Rockefeller wanted to stand out and be able to help both the economy and the people. On July 22nd, 1931, when construction of the structure began, New York's economy was in a horrendous. Unemployment rates for construction workers were extremely high when building began, and many business they went bankrupt. One of New York City's most recognized landmarks is Rockefeller Center, which is also where the Today program and Saturday Night Live are filmed and where ice skaters circle an ice rink surrounded by hundreds of different flags from around the world. This shows that the Rockefeller center is full or art and also CULTURE. The complex is extremely complex and spacious. Rockefeller Center is “the city inside a city,” The Rockefeller Center is where, every year, the famous Christmas tree lights up in this city. As it seemed to glide over the flooded plaza in front of a white granite background, an orchestra of water jets was accompanying its sculpture. Rockefeller Center would be decorated for Christmas every year by a Norway spruce that had soared to the height of 100 feet in 1948. German artist Michael Hammers' nine-and-a-half-foot star, which contains “25,000 crystals and a million facets”, has been the tree's crowning ornament since 2009.  publicist decided to establish the Christmas tree as a yearly custom in 1933 after being moved by the first tree. To finalize, despite these hard times, it was a representation of America's perseverance.

Work Cited 

     Brizak, Deanna. *History of New York City*, 14 Nov. 2016, https://blogs.shu.edu/nyc-history/2016/11/14/rockefeller-center/.

     Parrella, Christina. “Inside Rockefeller Center.” *NYCgo.com*, NYC & Company, 28 Nov. 2018, https://www.nycgo.com/articles/inside-rockefeller-center.

    Hzdg. “History at Rockefeller Center: NYC's Historical Landmark.” *Rockefeller Center*, https://www.rockefellercenter.com/history/.

      “History and Traditions of Rockefeller Center.” *TopView Sightseeing*, https://topviewnyc.com/attractions/top-of-the-rock.

       Person. “Building Rockefeller Center - and a Legacy: Christie's.” *How One Man Built Rockefeller Center - and Changed New York's Skyline | Christie's*, Christies, 1 May 2018,https://www.christies.com/features/How-the-Rockefellers-changed-the-New-York-skyline-9174-1.aspx.
