---
author: "Maxwell Hecht-Chaneski"
title: "The Classical Theatre of Harlem"
---

The Classical Theatre of Harlem is a Theater in 8 W 126th St, Uptown Manhattan that applies aspects of African culture to the plays it performs, reimagining Shakespeare’s works into diverse, culturally rich atmospheres that captivate and diversify the theatrical scene. The actors and producers also have a wide range of diversity in race, background and ethnicity, with most actors and faculty being people of color.

Founded in 1999 by the Harlem School of the Arts and directors Alfred Preisser and Christopher McElroen, It was not widely known during this time, and only started shifting their attention towards actors and playwrights of color in 2006.  During this time, an actor of theirs named Ty Jones, an experienced actor with an MFA in classical theatre, started becoming one of the driving forces in their theatrical endeavors. During the financial crisis of 2009, most businesses were financially compromised, especially so for small ones. And as a non-profit organization, it was clear the Classical Theater of Harlem was under a lot of financial vulnerability. They ended up about 400,000 dollars in debt and were struggling to pay it off. Ty Jones stepped in for this issue, because he believed in the inclusivity of the theatre and its potential to provide people of color with significant roles that impacted their career. The theatrical scene at the time wasn’t as inclusive, lead roles never being reserved for people of color. This was an especially noticeable trend in New York, as many different theater productions across the city were always relatively discriminatory when it came to their employment operations.

Ty Jones reached out to multiple organizations for advice, and executed a financial plan, involving a small donation campaign, that would eventually support the theater enough to keep it alive. This work and dedication would not go unnoticed. It ended up giving him the spot as the Producing Artistic Director and is currently the winner of an NAACP and OBIE award. The associate Artistic director, now Carl Cofield, is also an NAACP award recipient and an active participant in education programs.

It’s most recent reimagining of the Twelfth Night and Seize the King were vivid and fantastic, with the Twelfth Night being directed by Carl Cofield and utilizing Afrofuturist themes, bright colors in its lighting, and creative costume design. It was also not a theater restricted to a single building, so they’d be able to preform almost anywhere. One of their showings of The Twelfth night was held outside. They also have online performances such as their reading of Memnon. They received a sizable amount of acclaim, cementing the Classical Theater of Harlem as an opportunity to people of color in the theater for creative expression, education and success. They were even able to get attention from bigger names such as Ethan Hawke, a four-time Academy Award Nominee, which is set to join their Board of Directors. It provides authentic, culturally relevant performane and writing by including diverse, needful communities into the important roles of large-scale productions.

https://www.forbes.com/sites/risasarachan/2020/01/09/actor-ty-jones-who-once-saved-the-classical-theatre-of-harlem-now-presents-its-20th-season/?sh=3ca1917a533d

https://www.cthnyc.org/about-2/

https://playbill.com/article/the-classical-theatre-of-harlem-names-carl-cofield-new-associate-artistic-director

https://www.getty.edu/visit/cal/events/ev_3640.html

https://www.broadwayworld.com/off-broadway/article/Ethan-Hawke-Joins-The-Classical-Theatre-of-Harlem-as-Trustee-20230403