---
author: "Maxwell Hecht-Chaneski"
title: "Transy House"
---

In the East Village stood a small house, known in the 1970s as the STAR House. It was a small shelter for trans and otherwise LGBT individuals in the area that provided shelter, accommodations, and an avenue for LGBT activism for members and allies involved. This collective was noted for how grounded in the local community it was. It was founded by Stonewall Activists Marsha P. Johnson and Sylvia Rivera, and the landlord of the house, Michael Umbers, was an active supporter of the LGBT community.

Sadly, the STAR House only lasted about 8 months under the enormous rent, even with the financial accommodations provided by the Umbers. But this house still was one of the major movements that made a huge impact for the community therein. It was also inspired by the Stonewall riots, as was many other LGBT spaces in New York were. it established New York as a place with a triving, active community of LGBT individuals, and because of that, it caused inspiration for these other spaces to exist. This would also not be the first of its kind, as the Transy House was eventually formed in 1995, in Brooklyn, on 214 16th Street as inspired by the STAR House. Transy House was founded by Rusty Mae Moore and Chelsea Goodwin and was operated by them from 1995-2008.

This house, unlike the STAR House, wasn’t planned ahead as much as it started out as a simple hangout place and then became a haven for the community as a whole. Although a smaller collective, the project lasted up until 2008. What’s interesting about this space is how it was basically founded by the principle that trans people are intent to gravitate towards one another, and it poses the question of how effective trans safety and accommodation is when done on a local scale rather than organizational. It also stands as a testament to the events that came before it, as it fittingly matched each of the properties that the project’s roots had amassed. Just like The Stonewall Riots, this house was effective as it was less officially planned and more so provoked from local interactions. And just like the STAR House, it was able to provide accommodation and community to LGBT members over the years. Although a small project, the house set an example of what could be possible for locally sourced projects and collectives for the following years to come.

The STAR House and then the Transy House were both important because they could keep vulnerable people off the street, but also because in living together the community became very tight. A lot of the LGBT spaces today do not directly solve the issue of housing, but they do give healthcare, community, support and resources. These spaces have largely been kept down by the ever-present existence of capitalism in an economically-driven environment, and to hold its own is one of the most important abilities the LGBT community can achieve. That is, to rise above a dying result of Stonewall and into a self-sufficient community that supports itself through community.

https://www.villagepreservation.org/2020/10/29/revolutionaries-on-east-second-street-
the-star-house/

https://www.audacy.com/1010wins/articles/transy-househttps://www.nyclgbtsites.org/site/transy-house/

https://slashqueer.com/the-emergence-loss-of-trans-spaces-in-new-york-city-transcript

https://www.nyclgbtsites.org/site/transy-house/

[https://gaycenter.org](https://gaycenter.org/)