---
title: "Bryant Park"
author: "Chaim Ilowitz"
---

Over twelve million people visit Bryant Park every year, making it one of the world’s busiest public spaces. With all the activities, including games, art, ping pong, putting, reading, and chess, people come from all over the city to stop by Bryant Park.

When the British occupied what is now the United States, they designated specific areas of land for specific purposes. One of those pieces of land is the area of the city we now know as The New York Public Library and Bryant Park. In 1686, this area was to be “public space.”

Fast-forward to the 1930’s, Bryant Park was due for a redesigning. The renovation began with “tearing down the L train tracks and replacing them with a subway stop” (Classic New York History). In addition, the park’s land grade was raised and they surrounded the park with tall hedges. While perfect at the time, these change made Bryant Park a dangerous place a few decades later. Drug dealers, psychiatric patients, and rapes were commonplace at the park. People were terrified of going into the park.

Something had to change, and by the 1990’s, a second redevelopment plan was put into place. The first agenda was lowering the park to street level. The tall and thick hedges surrounding the park were torn down as well, making the park visible from the streets. The park was starting to become a place that people frequently visited. The idea was that the more people that visited the park, the safer it will be. So they starting putting more things into place, such as games and events, to make the park more welcoming and open to anyone. 

Anyone can tell you that parks are an important component to the well-being and prosperity of modern society. The point of all these renovations and revitalizations were to make Bryant Park a place that people actually wanted to go to. Furthermore, they wanted to make it a neighborhood people would want to live in. 

The area surrounding Bryant Park was, and still is, a business district. So it is important to be able to come home to a quiet environment, feeling safe that you will not get mugged. 

Packed into a tight city, it is tough to imagine the idea that there can be a park where you can go for a quiet walk, or a place to play some game sand blow off some steam with friends. And yet, that is exactly what Bryant Park is. If you need a calm place to visit and relax, Bryant Park is the place to go.

*Bryant Park NYC*. (2023, April 29). [https://bryantpark.org/](https://bryantpark.org/)

*History of Bryant Park in New York*. (n.d.). Retrieved April 29, 2023, from [https://traveltips.usatoday.com/history-bryant-park-new-york-52780.html](https://traveltips.usatoday.com/history-bryant-park-new-york-52780.html)

Hughes, C. J. (2017, November 8). Bryant Park: A Growing Neighborhood in Central Manhattan. *The New York Times*. [https://www.nytimes.com/2017/11/08/realestate/living-in-bryant-park.html](https://www.nytimes.com/2017/11/08/realestate/living-in-bryant-park.html)

Repka-Franco, V. (2018, August 24). *History Of Manhattan’s Bryant Park—ClassicNewYorkHistory.com*. [https://classicnewyorkhistory.com/history-of-manhattans-bryant-park/](https://classicnewyorkhistory.com/history-of-manhattans-bryant-park/)

Song, Y., Fernandez, J., & Wang, T. (2020). Understanding Perceived Site Qualities and Experiences of Urban Public Spaces: A Case Study of Social Media Reviews in Bryant Park, New York City. *Sustainability*, *12*(19), Article 19. [https://doi.org/10.3390/su12198036](https://doi.org/10.3390/su12198036)
