---
tite: "Empire State Building"
author: "Chaim Ilowitz"
---

In 1928, the Waldorf Astoria Hotel on Fifth Avenue was sold to the Bethlehem Corporation for \$20 million. This building was later demolished, and it was to become the Empire State Building. By 1930, construction began, with plans to make it the world's first 100+ story building, which was thought to be impossible at the time. It ended up taking a mere 1 year and 45 days to finish construction. To this day, it remains "one of the most distinctive and famous buildings int he United States" (Britannica).

At that time, there was a fierce competition to build the tallest building in the world. The Chrysler Building, also in Manhattan, competed and won by 1929. However, by the time the Empire State Building was complete, it over took the Chrysler Building, and became the tallest building in the world, standing at now 1,454 feet high. By 1972, the World Trade Center overtook the Empire State Building as the tallest building in the world.

Going back further in history, the area that the Empire State Building now stands was said to be the place where George Washington's troops retreated to after the Kips Bay battle during the Revolutionary War.

The plans for the Empire State Building was made during the roaring twenties, when there was a boom in the economy and an explosion of commercial buildings rose up in Manhattan. However, the roaring twenties would come to an abrupt halt on Black Thursday, when "the stock market crashed, the banks failed, companies went belly-up, and the country would soon be plunged into the Great Depression" (City Signal). The Great Depression did not deter the plans to build the Empire State Building. It even helped the economy, creating 3,439 jobs in a time when unemployment rates were rapidly rising.

Construction of the Empire State Building was not all what it is said to be. "Official accounts report that five workers died during the construction of the building" (City Signal), with other accounts reporting even higher numbers. Construction work in the 30's did not have the same protection and safety equipment that we have today.

If you are anywhere near Manhattan, the Empire State Building is a sight worthy of visiting at least once. Public transportation makes it extremely easy to get there, with even a sightseeing bus that makes a stop there. Additionally, there are exhibits and observation decks at the Empire State Building, those requiring a ticket for entry. The observation decks on the 102nd floor give a view of the City only accessible from the Empire State Building. It is a beautiful site to visit and take in.

Bice, E. (2022, December 28). The Complete History of the Empire State Building. *CitySignal*. <https://www.citysignal.com/empire-state-building-history-facts/>

*Empire State Building \| Height, Construction, History, & Facts \| Britannica*. (2023, April 27). <https://www.britannica.com/topic/Empire-State-Building>

*Empire State Building Dedicated*. (n.d.). HISTORY. Retrieved May 6, 2023, from <https://www.history.com/this-day-in-history/empire-state-building-dedicated>

*History \| Empire State Building*. (n.d.). Retrieved May 6, 2023, from <https://www.esbnyc.com/about/history>

Norah, L. (2020, July 25). *Guide To Visiting The Empire State Building in New York City---Everything You Need to Know!* Finding the Universe. <https://www.findingtheuniverse.com/empire-state-building-guide/>
