---
author: "Cobe Liu"
title: "Julius and Ethel Rosenberg"
date: "5/11/23"
---

Julius and Ethel Rosenberg were a couple from New York City who were accused of spying for the Soviet Union during the Cold War. Born in 1918, Julius was an engineer and a member of the Communist Party, while Ethel, born in 1915, worked a secretarial job and advocated for worker’s rights.

The couple's involvement in espionage activities started during World War II when Julius was recruited by the Soviet intelligence agency, NKVD. He was tasked with obtaining classified information about the atomic bomb and other military secrets. Ethel soon joined her husband in these activities, and the couple began passing on information to their Soviet handlers.

In 1950, the FBI arrested the Rosenbergs and charged them with conspiracy to commit espionage. The trial was highly controversial, with many people believing that the couple was unfairly targeted because of their political beliefs. However, as the case progressed, the prosecution presented evidence that the Rosenbergs had passed on classified information to the Soviet Union, including details about the atomic bomb. Additionally, since then more information has surfaced or been declassified, furthering the case against the Rosenbergs. Even Khrushchev, can be quoted acknowledging the significance of Ethel and Julius’s contributions in his memoir. 

According to testimony from Ethel Rosenberg's brother, David Greenglass, he was recruited by Julius Rosenberg to provide classified information about the atomic bomb. Greenglass was a machinist at the Los Alamos laboratory in New Mexico, where the atomic bomb was being developed. He passed on sketches and descriptions of the bomb's design to Julius, who then passed them on to the Soviet Union. Ethel was also implicated in the conspiracy, as she was said to have typed up some of the classified information that Julius passed on to the Soviets.

Whether Ethel typed up the reports is unclear. Originally, David’s wife, Ruth, was implicated for assisting in pass of information between David and Julius. However, in David’s second testimony he removed all mention of his wife’s involvement by pinning a lot on Ethel. In an interview conducted by Sam Roberts, when asked if his sister was the one who typed up the classified information he responded: “I don’t remember that at all. I frankly think my wife did the typing, but I don’t remember. My wife is more important to me than my sister. Or my mother or my father, O.K.? And she was the mother of my children.” Due to this interview among other indications of Ethel’s minimal role, many believe the charges against Ethel as largely unfounded and unjust. 

Despite protests from around the world, the Rosenbergs were found guilty and sentenced to death. They were executed by electric chair on June 19, 1953. While Julius was found dead after the first shock. Ethel’s heart was still beating after the initial 3 shocks and was not found dead until 2 more shocks were administered.

# Sources

Jenkins, John. *Julius and Ethel Rosenberg | Biographies & Facts | Britannica*. 1 May 2023, [https://www.britannica.com/biography/Julius-Rosenberg-and-Ethel-Rosenberg](https://www.britannica.com/biography/Julius-Rosenberg-and-Ethel-Rosenberg).

“Julius Rosenberg - Nuclear Museum.” *Https://Ahf.Nuclearmuseum.Org/*, [https://ahf.nuclearmuseum.org/ahf/profile/julius-rosenberg/](https://ahf.nuclearmuseum.org/ahf/profile/julius-rosenberg/). Accessed 8 May 2023.

McFadden, Robert D. “David Greenglass, the Brother Who Doomed Ethel Rosenberg, Dies at 92.” *The New York Times*, 14 Oct. 2014. *NYTimes.com*, [https://www.nytimes.com/2014/10/15/us/david-greenglass-spy-who-helped-seal-the-rosenbergs-doom-dies-at-92.html](https://www.nytimes.com/2014/10/15/us/david-greenglass-spy-who-helped-seal-the-rosenbergs-doom-dies-at-92.html).

“Khrushchev on Rosenbergs: Stoking Old Embers.” *The New York Times*, 25 Sept. 1990. *NYTimes.com*, [https://www.nytimes.com/1990/09/25/world/khrushchev-on-rosenbergs-stoking-old-embers.html](https://www.nytimes.com/1990/09/25/world/khrushchev-on-rosenbergs-stoking-old-embers.html).

Radosh, Ronald, and Steven Usdin. “Opinion | What the K.G.B. Files Show About Ethel Rosenberg.” *The New York Times*, 13 Aug. 2015. *NYTimes.com*, [https://www.nytimes.com/2015/08/13/opinion/what-the-kgb-files-show-about-ethel-rosenberg.html](https://www.nytimes.com/2015/08/13/opinion/what-the-kgb-files-show-about-ethel-rosenberg.html).