---
title: "Macaulay Honors College"
author: "Lucca O'Connor"
---

The Macaulay Honors College campus is something I’m sure most of us in class are familiar with. Stationed at 35 West 67th Street, the college is highly regarded. On campus various events are held by the many clubs that Macaulay has, allowing for students to attend and wind down after the stress and busywork of their classes.

Besides the physical location of the college, Macaulay offers a financial aid program in the form of an Honors Program across eight separate CUNY colleges, these being Baruch College, Brooklyn College, City College, College of Staten Island, Hunter College, John Jay College of Criminal Justice, Lehman College, and Queens College

Students are given full year tuition for four years at a campus of their choice. In order to be accepted into this program, however, a lot needs to be considered.

“Admissions to the The Macaulay Honors College will be based upon

- High school grades
- SAT I/ACT scores
- An essay
- Recommendations
- In some cases an interview

To continue to receive the The Macaulay Honors College financial package students must remain in good academic standing as defined by the The Macaulay Honors College.” (CUNY Macaulay Honors Program)

Students are also offered study grants in order to further go into their research.

With all these perks offered by the main college, you would think that being in the Macaulay Honors Program is easy. One thing you’re told about before you start your first semester in the program is the various requirements you must be extremely diligent about. During your four years in the program, students must complete the various pathways at the student’s campus.  They are required to finish at least 30 hours of community service before junior year, recommended about 10 hours per year.  These specific requirements are detailed on the Macaulay website.  Students are also asked to work at an internship or study abroad. 

As a student in the Macaulay program, the work has been difficult.  As it is my first year, it is still relatively manageable, with the only Macaulay related work I’ve done so far is take the seminars and do a lot of community service on my spare time, on top of keeping my GPA in a good place.  Macaulay students also get to work with advisors that are assigned to them.  You’re required at least one meeting per semester, just as a way to update your advisors and prepare for the next semester, as well as the inevitable final thesis that is written in the senior year.

The Macaulay Honors Program is a challenge, but the engaging work done with peers and the freedom that is offered in the seminar classes allows for proper growth for the student.  Depending on the professor, students will get time to explore sites off campus to write about in the various assignments for class. It makes for a lot of great opportunities that you would not otherwise have access to.

Sources:

[Macaulay Honors College](https://macaulay.cuny.edu/)

[William E. Macaulay Honors Program  –  The City University of New York](https://www.cuny.edu/financial-aid/scholarships/william-e-macaulay-honors-program/)

[Pathways for Academic Year 2022-2023 - Brooklyn College](https://www.brooklyn.edu/caass/pathways/2022-2023/)

[](https://macaulay.cuny.edu/student-life/community-service/community-service-requirements-and-policies/)

[Internships](https://macaulay.cuny.edu/after-macaulay/career-development/internships/)
