---
title: "One World Observatory"
author: "Lucca O'Connor"
---

For prices around \$30 (\$34 for adults, \$32 for seniors, and \$28 for children), one can witness what is widely considered to be one of the best views in all of New York City. Where else would you go to see this but the One World Trade Center. The 102nd floor of the 1,776 foot building lies the One World Observatory. The site was first opened on May 29 in 2015, attracting tourists far and wide and garnering immense support.

It was in New York City's Financial District where the Twin Towers once stood. However, after the tragic attacks on 9/11 resulted in the destruction of the towers, designs started to come up for what would stand in their place. Four years later, "a project was presented by architect David Childs called 'Freedom Tower' and was finally accepted." (Memo). Once construction started in 2006, it would take another 7 years for the Freedom Tower to reach completion, being done so on May 10 2013. The building was still closed to the public at this point, though it only took another two years for the general public to be allowed into the now One World Trade Center.

Other information from Pars Memo, a tourist who went multiple times to the site, include:

-- It measures 546 meters high (1776 feet), which corresponds precisely to the year of the Declaration of Independence of the United States.

-- It is the tallest building in North America.

-- If we remove the antenna, measuring 129 meters (almost ¼ of tower height), it would be the second tallest building after the "Willis Tower" in Chicago that measures 527 meters with 110 floors.

-- It has 104 stories.

-- The observatory is on floors 100, 101, and 102.

-- The building has 73 elevators, but only five are used for the OWO (One World Observatory). The other lifts are used for security and office employee's floors 19 to 100.

-- The estimated cost is 3.9 billion dollars.

Anyone interested in booking a trip to the observatory should do so in advance, as lines can get *pretty* long. Although according to most who go, the trip is worth it, as a complete 360 degree view of the city from that height is a sight to behold.

Sources:

[One World Observatory \| Manhattan, NY \| Attractions in Financial District, New York](https://www.timeout.com/newyork/attractions/one-world-observatory-manhattan-ny)

[Discover the One World Observatory](https://www.new-york-city-travel-tips.com/one-world-observatory/)
