---
title: "Macy's Thanksgiving Day Parade"
author: "Christopher Soto"
---

On November 23, 2023 New York City will showcase its 97th Macy's Thanksgiving Day Parade. This annual event features giant balloons up in sky, creative floats, marching bands, performers, and performance groups, with thousands of spectators in the sidelines. From 9:00 AM to noon, the parade starts at 77th St and Central Park West and heads down to 34th Street to Macy's Herald Square. Since 1939, families across the US can experience this wonderful event on the television through the NBC channel.

In 1924 Macys opened up an enormous store at Herald Square. The store covers an entire block! To celebrate, on a Thanksgiving morning, Macy's hosted a “holiday spectacle to alert the masses” (Bryant 1). This event was good to attract shoppers into the new department store, however this was not the thanksgiving parade everyone knows today. This parade was Christmas themed! 

The big balloons New York sees today where absent in 1924. The parade was significantly small, there where floats themed after Mother Goose characters like little red riding hood, zoo animals marching in the streets, four different marching bands, and Macy employees dressed up as clowns, knights, and cowboys. Despite the small parade, the route was larger than the one today! In 1924 the parade started at 145th street Convent avenue in Harlem and continued to Herald Square, where the Macys store is located. The parade ended with an ornamental float with Santa Claus; once Santa's float reached the new store a unique showcase played out to attract more guest into the store for the holidays. Three years later, in 1927, Macy's would host its very first Thanksgiving day parade. 

In 1927, the animals of the zoo where replaced by balloons, and later iconic cartoon characters. Like all things, the first attempts had issues. There was lots of trail and error, but the idea still remained in play. Balloons would burst, fly away, and get lost. As a response each year safety measure would be updated to the balloons. The balloons began to have the address printed so that they are mailed back to store. 

Throughout its years, the parade continued throughout any economic crisis, however during the events of world war ll, the parade was suspended because rubber and helium were materials needed for the war. After the assassination of president John F, Kennedy there was debate if the parade should be in play, and at the end of the day it happened as a way to lift up the “American spirit”.

Today, the parade features dozens of balloons, over 30 floats, over a thousand dancers and cheerleaders, over 700 clowns, marching bands from around the country, and a total of over 8000 participants in the parade. The parade ends by welcoming the holidays into the big apple with Santa at the end of the parade. 

**Annotated Bibliography**

Development, Macy’s Interactive. “Macy’s Thanksgiving Day Parade 2021 - Thanks for Joining Us.” *Macy’s Thanksgiving Day Parade*, [https://www.macys.com/social/parade/lineup/](https://www.macys.com/social/parade/lineup/). Accessed 17 May 2023.

Feb. 07, Kelly Bryant Updated: and 2023. “Everything to Know About the Macy’s Thanksgiving Day Parade 2022.” *Reader’s Digest*, 24 Nov. 2021, [https://www.rd.com/article/macys-thanksgiving-day-parade/](https://www.rd.com/article/macys-thanksgiving-day-parade/).

“The First Macy’s Thanksgiving Day Parade.” *HISTORY*, 22 Nov. 2021, [https://www.history.com/news/the-first-macys-thanksgiving-day-parade](https://www.history.com/news/the-first-macys-thanksgiving-day-parade).

“The 97-Year History of the Macy’s Thanksgiving Day Parade.” *6sqft*, 17 May 2023, [https://www.6sqft.com/a-nyc-tradition-the-history-of-macys-thanksgiving-day-parade/](https://www.6sqft.com/a-nyc-tradition-the-history-of-macys-thanksgiving-day-parade/).

*10 Things You Didn’t Know about the Macy’s Thanksgiving Day Parade | 6sqft*. [https://www.6sqft.com/10-things-you-didnt-know-about-the-macys-thanksgiving-day-parade/](https://www.6sqft.com/10-things-you-didnt-know-about-the-macys-thanksgiving-day-parade/). Accessed 17 May 2023.
