---
title: "Times Square Ball Drop"
author: "Christopher Soto"
---

To welcome in the new year, thousands of people head over to Times Square on the night of December 31 to watch the ball drop. Celebrating New Years in Times Square began in 1904, but in 1907, a ball drop at 1 Times Square was added into the celebration. This marked to beginning of the universal symbol the world knows today. 

The concept of the ball drop began 1883. On top of the royal observatory in Greenwich, England, a time ball was dropped every afternoon at 1. This practice allowed captains of nearby ships to set their chronometers. A chronometer is a device that measure time, similar concept to a modern day watch. After the success in England, time balls spread around the world.

Since 1907, New York has presented 7 different designs of the ball to welcome in the new year. The first New Years eve ball was 700 pounds! The ball was designed by Jacob Starr, a young immigrant metal worker. The ball measured five feet in diameter; was made of iron and wood; and was covered with one hundred 25 watt bulbs. As the years went on the ball got bigger and brighter. The materials used were up to date with modern technologies. For example, in 2007, the ball was covered with LED technology to replace the light bulbs of the past. So much can happen in a century!  

Today, 2023, the ball is 12 feet in diameter, weighing 11,875 pounds! The ball is covered with 2,688 crystals that vary in size, and illuminated by 32,256 LEDs. The crystals are categorized into 9 groups of 192. Each group represents a spiritual gift such as love, kindness, and happiness. The remaining 960 represent imagination that are cut in a way to reflect one another to mirror the reflections of each other inspiring one another. 

A little after 6pm on New Years eve, the ball is raised up. To watch the event, people gain their spot as they come in. Interestingly enough, many wait early in the morning out in the cold to guarantee a nice viewing angle. Once the clock hits 11:59pm the ball begins to decent as the one minute countdown begins. Once the ball reaches the bottom tons of confetti is thrown out, and people celebrate aloud at Times Square and in their homes.  

**annotated bibliography** 

*New Year’s Eve 2023 by New Year’s Eve*. *livestream.com*, [https://livestream.com/newyearseve/events/10381259?t=1684353383](https://livestream.com/newyearseve/events/10381259?t=1684353383). Accessed 17 May 2023.

admin. *NYE History & Times Square Ball*. 10 May 2017, [https://www.timessquarenyc.org/times-square-new-years-eve/nye-history-times-square-ball](https://www.timessquarenyc.org/times-square-new-years-eve/nye-history-times-square-ball).

“Times Square Ball Drop.” *NYCgo.Com*, 31 Dec. 2022, [https://www.nycgo.com/events/times-square-new-years-eve-ball-drop](https://www.nycgo.com/events/times-square-new-years-eve-ball-drop).

Fadulu, Lola. “What to Know About the Times Square Ball Drop on New Year’s Eve.” *The New York Times*, 28 Dec. 2022. *NYTimes.com*, [https://www.nytimes.com/2022/12/28/nyregion/new-years-eve-ball-drop-how-to-watch.html](https://www.nytimes.com/2022/12/28/nyregion/new-years-eve-ball-drop-how-to-watch.html).

Gottschalk, Andy. “Culture Of Time: The Hidden Horological History Of The Times Square Ball Drop.” *Hodinkee*, 4 Jan. 2023, [https://www.hodinkee.com/articles/times-square-ball-drop-time-ball-history](https://www.hodinkee.com/articles/times-square-ball-drop-time-ball-history).
