---
tite: "Rockefeller Center Christmas Tree"
author: "Christopher Soto"
---

New York City marks the beginning of the holiday season at Rockefeller Center with the annual tree lighting ceremony. Having over 50,000 multicolored led lights, decorations, and a 900 pond star topped with approximately 3 million crystals! Such additions allow the bright glow of the massive tree to be visible from a distance within range. 

The beginning of this tradition occurred in December of 1931, Post Depression era, when workers at Rockefeller Center cooperated to buy a 20 foot Christmas tree. The tree was decorated with lots of household items such as handmade garlands. Later, in 1933, it was decided that Rockefeller center will have an annual Christmas tree lighting ceremony, and in December of the same year, New York City saw the first ever tree lighting ceremony. 

Since then, each year the holiday spirit at Rockefeller Center continues to get bigger and brighter. For example, in celebration of the brand new ice rink, two trees where put up in December of 1936. During World War ll, there was a material shortage so three smaller trees where put up at Rockefeller Center decorated in red, white, and blue. From 1942 to the end of the war the trees were unlit. In December of 1969, the angel figures at channel gardens made its first appearance. These amazing works where sculpted out of metal wire by Valerie Clarebout, an international painter and sculptor. To wrap up the list of events, on December of 1999 the tallest tree was up, standing at 100 feet tall! 

Nowadays, on the night of November 30, about 500,000 people visit the Christmas tree ceremony! With opening performances by artist, Christmas carols, and bands, the ceremony is one to be experience at least once. During the month of December the tree is on daily from 5am to 12am, the only exceptions being on Christmas Day in which the lights are on for 24 hours. Another exception is on New Years Eve because the lights are on from 5am to 9pm. Plan accordingly! To get the most of the holiday spirit plan a visit to the Radio City Rockettes's Christmas spectacular or the 12 angels at channel gardens. The large variety of shops at Rockefeller Center allow people to do some holiday shopping as well! and if hungry, Rockefeller Center has over 30 dinning options to choose from.     

The holiday spirit does not stop once the tree lights go down. When the holiday season is over the tree is donated to Habitat for humanity, a non profit housing organization. The organization partners up with families and individuals to build and improve affordable homes. Since 2007 the Rockefeller Center Christmas Tree is made into lumber for habitat homes. When the tree is taken down, it gets cut down into large pieces and then transported to a mill in New Jersey to make the wood have the appropriate shape for construction.

Remember the tree is free to visit for the whole month of December! 

**Bibliography** 

*🎄 Rockefeller Center Christmas Tree Lighting | NYC Winter Events*. [https://www.rockefellercenter.com/holidays/rockefeller-center-christmas-tree-lighting/#viewing-details](https://www.rockefellercenter.com/holidays/rockefeller-center-christmas-tree-lighting/#viewing-details). Accessed 8 May 2023.

*Celebrate The Holidays at Rockefeller Center*. [https://www.rockefellercenter.com/holidays/#holidays-at-rockefeller-center](https://www.rockefellercenter.com/holidays/#holidays-at-rockefeller-center). Accessed 12 May 2023.

Press, The Associated. “A Giant Christmas Tree Is Once Again Raised at New York City’s Rockefeller Plaza.” *NPR*, 12 Nov. 2022. *NPR*, [https://www.npr.org/2022/11/12/1136294632/holiday-christmas-tree-new-york-city-rockefeller-center](https://www.npr.org/2022/11/12/1136294632/holiday-christmas-tree-new-york-city-rockefeller-center).

“Rockefeller Center Christmas Tree’s Journey into a Habitat Home.” *Habitat for Humanity*, [https://www.habitat.org/stories/rockefeller-center-christmas-trees-journey-habitat-home](https://www.habitat.org/stories/rockefeller-center-christmas-trees-journey-habitat-home). Accessed 12 May 2023.

“Rockefeller Center Christmas Tree through the Years.” *New York Daily News*, 29 Nov. 2022, [https://www.nydailynews.com/new-york/rockefeller-center-christmas-tree-gallery-1.1537082](https://www.nydailynews.com/new-york/rockefeller-center-christmas-tree-gallery-1.1537082).