---
author: "Saadiya Taylor"
title: "The MET"
---

An establishment built on the basis of creating a permanent art gallery in New York, The Metropolitan Museum of Modern Art has provided access to art education since its public opening in 1870. In the organizational years from 1869 - 1871, the plan to initiate the museum movement was led by the infamous lawyer, John Jay, as he motivated civic leaders, businessmen, artists, art collectors, and philanthropists to support his cause. Jay believed that the creation of this national gallery of art and a museum of historical relics that were collected, safely preserved, and displayed would be beneficial to the people. The MET was to be an art institution that was free from the influence of the government or control from a singular person that could negatively affect it.

The first housing of the MET was the Dodworth Building at 681 Fifth Avenue, between 53rd and 54th Street. Although the building was originally altered to be a dance academy, it was admired for its perfect construction to showcase the purpose of the museum, including a skylight that would inspire the incorporation of a picture gallery. The lease of the Dodworth building was set to be occupied from December 1, 1871- May 1, 1874; however, the trustees of the museum were in search of a more permanent residence. The following site of interest for the MET was Manhattan Square, as well as as the modern-day location for the American Museum of Natural History. On April 5, 1871, legislation passed for the Board of Commissioners of the Department of Public Parks of New York City "authorized to construct, erect, and maintain upon that portion of the Central Park formerly known as Manhattan Square, or any other public park, square, or place in the city…a suitable fireproof building for the purpose of establishing and maintaining therein a Museum and Gallery of Art by The Metropolitan Museum of Art" (Howe, 1946). While the construction of the park was prepared, the second home of the Museum was the Douglas Mansion located at 128 West Fourteenth Street, between Sixth and Seventh Avenues. The spacious layout of the house and grounds provided the opportunity for the MET to display their present collection, along with antiquities and other objects they desired to maintain through loan exhibitions and the expansion of new galleries if necessary. The house was accessible via public transportation. Occupancy of the Douglas Mansion concluded on March 30, 1880, when the MET moved to its present site on Fifth Avenue and 82nd Street in Central Park.

Following the official settlement of the MET, the fundamentals it was established on have not been lost to history. The museum continues to expand its collection and further employ techniques to educate the public. Containing over 490,000 works of art, the “major collection includes American paintings and sculpture; European paintings; Egyptian art; arms and armor; the art of Africa, Oceania, and the Americas; ancient Near Eastern art; Asian art; costumes; drawings and prints; European sculpture and decorative arts; Greek and Roman art; Islamic art; medieval art; modern and contemporary art; musical instruments; photographs; and the Robert Lehman Collection.” (Villaespesa, 2019). When redesigning its website in 2011, the MET prioritized providing information to scholars and accessibility to the public. The website allows users to find artworks: artist or culture, date, medium, dimensions, classification, and whether it is on display in the galleries. Also includes amongst other features  “375,000 images of artworks in the public domain under a Creative Commons Zero license” (Villaespesa, 2019). In addition to the online services, the in-person educational services allow students to receive gallery tours, lectures, and study groups from museum staff. When visiting the MET, children have a “junior museum” dedicated to them so they are able to study exhibits that they are interested in. Schools, institutions, teachers, and labor unions are also allowed to obtain photographs, prints, and slides. Overall, the impact of the MET on the arts proceeds to be redefined as they dedicate themselves to providing consecutive artistic exposure.

Citations:

1. Howe, Winifred E. A History of the Metropolitan Museum of Art, with a Chapter on the Early Institutions of Art in New York, by Winifred E. Howe. 1946.

2. Laidlaw, Christine Wallace. “The Metropolitan Museum of Art and Modern Design: 1917-1929.” The Journal of Decorative and Propaganda Arts, vol. 8, 1988, pp. 88–103, https://doi.org/10.2307/1503972.

3. Villaespesa, Elena. “Museum Collections and Online Users: Development of a Segmentation Model for the Metropolitan Museum of Art.” Visitor Studies, vol. 22, no. 2, 2019, pp. 233–52, https://doi.org/10.1080/10645578.2019.1668679.

4. Powel, Lydia Bond. Television and the Metropolitan Museum of Art, a Study by Lydia Bond Powel ... Under a Grant by the Metropolitan Museum of Art, December, 1945. The Metropolitan Museum of Art, c1946, 1946

5. *History of the museum*. The Metropolitan Museum of Art. (2020, July 1). https://www.metmuseum.org/about-the-met/history