---
author: "Saadiya Taylor"
title: "The Chrysler Building"
---

Lexington Avenue 50 years prior stood an old woman's white house and a herd of goats. Eventually, this land would be bought by William H. Reynolds, a New York Senator turned real estate developer, who leased out East Lexington Avenue between 42nd and 43rd Street. Reynolds assigned William Van-Alen to design an 808-foot skyscraper; however, Van-Alen had not previously done a project of this scale as he specialized in designing small story shops and restaurants. After Reynold began to experience financial difficulties, he sold the project to Walter P. Chrysler in 1928 for $2 million including the land, building plans, and Van-Alen. Chrysler moved to New York City to take over the Willys-Overland Motor Company and wanted to build a headquarters that was the tallest building in the world. Chrysler demolished the progress made by Reynolds to start over along with increasing the height from 67 to 77 stories (1046 feet). The height of the building would surpass the 625-foot Woolworth Building, which had held the title since 1913; however, the empire state building eventually surpassed the Chrysler Building at 1454 feet.

Although Van-Alen had incomplete ideas, Chrysler inherited his design plan while making additions to express his personal style to make a successful team. The architectural design of the Chrysler Building was an Art Deco style originating in France during World War I. This Art Deco style is heavily influenced by geometric shapes and fine artwork also often involving expensive materials that showcase wealth and class. Despite the French Art Deco style of the building, there are references to Chrysler's automobile experience. This can be seen in the gargoyles on the building resembling the Plymouth automobile produced by Chrysler along with radiator caps, hubcaps, and tires. Finally, the building finished construction with no casualties and a cost of $14 million in 1930.

On April 1, 1930, the Chrysler Building officially welcomed tenants. Located two blocks from Grand Central Terminal, the building served thousands of people who engaged in business transactions and/or visiting the observatory in addition to the approximate 15,000 tenants and employees. The building consisted of a home environment as Chrsyler included necessities he believed executives and office personnel would need to conduct their work, but also even luxurious amenities to promote more efficient operation. The building became a community with its own Schrafft's restaurant, Terminal barber shop, stores, beauty parlor, two gymnasiums, and two emergency hospitals. The inclusions building display the innovation of Chryslers planning as these advancements were not considered by other building developers. 

The Chrysler building was prospering and an improvement to the community; however, it began to experience financial difficulties from the stock market crash and Great Depression that depleted resources. Despite the increasing disparity between economic classes, the Chrysler building was a celebration of the prosperity available from American Industrial endeavors.

Citations: 

1. The Chrysler Building. Chrysler Tower Corporation, c1930, 1930.
    1. Delaney, Alida. “Issue No. 7 - Spring 2011 - Marymount Manhattan College.” *The Chrysler Building and the History Behind an American Architect*, 2011, www.mmm.edu/departments/art/artfusion/artfusion_news_spring_2011.pdf.
2. Petersen, Jessica and Springer, Daniel, "The Chrysler Building" (2021). *2021 Undergraduate Research Showcase*. 20. [https://scholarworks.boisestate.edu/under_showcase_2021/20](https://scholarworks.boisestate.edu/under_showcase_2021/20)
3. Cobb, Harold. "The Chrysler building." *Advanced Materials & Processes*, vol. 168, no. 4, Apr. 2010, pp. 28+. *Gale Academic OneFile*, link.gale.com/apps/doc/A223907337/AONE?u=cuny_broo39667&sid=googleScholar&xid=660584c7. Accessed 19 May 2023.
4. Stranges, John B. “Mr. Chrysler’s Building: Merging Design and Technology in the Machine Age.” *Icon*, vol. 20, no. 2, 2014, pp. 1–19. *JSTOR*, http://www.jstor.org/stable/43488017. Accessed 20 May 2023.