---
title: "Chelsea Market"
author: "Abigail Tenenbaum"
---

According to the official Keens Steakhouse website, Keens is the “only survivor of the Herald Square Theater District”. Before becoming a restaurant, Keens just ran as a rendezvous spot for the Lambs Club, a private social club for literary and theater figures. The restaurant itself was established in 1885, independent from the Lambs Club. 

Albert Keen was the founder of the restaurant, as well as manager of the Lambs Club at the time of the restaurant’s opening. He was a reputable figure in the Herald Square Theater District, both through his restaurant and as a Lambs Club member. Keens Chophouse was right near Garrick Theater; actors would sneak in through the back door (in full costume and makeup) seeking to “fortify themselves” with a quick drink during intermission. 

Besides just actors, Keens was frequented by various playwrights, producers, and journalists for its Pipe Room and churchwarden pipes. The pipes themselves were brought in from the Netherlands, as many as 50,000 every 3 years. Because the clay pipes were too fragile to carry around, a pipe warden registered and maintained the pipes, while pipe boys would move the pipes from storage to their owners and then back into stored safety. The Pipe Club at Keens had over 90,000 members registered. Numerous famous figures regularly visited to smoke at the restaurant, such as Teddy Roosevelt, Babe Ruth, Albert Einstein, and J.P. Morgan. Today, Keens has the largest collection of churchwarden pipes in the world. Many of them are lined up along the ceiling, strapped tight next to one another. More are displayed around the restaurant, especially those from more recognizable names. 

Keens is ultimately part-restaurant, part-museum. The inside of the restaurant is all carved dark wood and historical artifacts collected over the years from its various patrons. It can serve up to 750 customers in a night in its various rooms, each named after a notable figure, whether it be US history or Keens’s. The Lincoln Room, for instance, has various Abraham Lincoln memorabilia. There’s a handwritten version of the Gettysburg Address framed on the wall, but most notably, Keens has the blood-spattered playbill that Lincoln held in his hands the moment of his death. Next to the playbill is an article detailing how the playbill made its way to Keens Steakhouse. Another room in the restaurant is named after Lillie Langtry, a famous actress and paramour to King Edward of England. She sued Keens after being denied access to the gentlemen-only restaurant, eventually winning the case. After the court case, Keens put up a sign saying, “Ladies are in luck, they can dine at Keens.” 

Keens is held in high regard for its high-quality steaks. Its most famous dish are the mutton chops, but it’s far from the only food that Keens serves. Keens stores filet mignon, prime ribs, lamb racks, and short and strip loins in their own dry aging room. The meats are aged for three weeks onsite before being used. The room holds around 20,000 lbs of meat, the number varying more or less depending on the season. 

Serving steak since 1885, Keens Steakhouse is a restaurant holding steadfast to its long-held position in a near-entirely changed neighborhood. 

Keens Steakhouse. “History of Keens,” n.d. [https://www.keens.com/historyofkeens/](https://www.keens.com/historyofkeens/).

Kludt, Amanda. “The History of Keens, The 126-Year-Old House of Mutton.” *New York Eater*, n.d. [https://ny.eater.com/2011/7/27/6670601/the-history-of-keens-the-126-year-old-house-of-mutton](https://ny.eater.com/2011/7/27/6670601/the-history-of-keens-the-126-year-old-house-of-mutton).

Olmsted, Larry. “Great American Bites: Keens Steakhouse, NYC’s Oldest, Best,” March 22, 2012. [https://abcnews.go.com/Travel/great-american-bites-keens-steakhouse-nycs-oldest-best/story?id=15976470](https://abcnews.go.com/Travel/great-american-bites-keens-steakhouse-nycs-oldest-best/story?id=15976470).

The Lambs, Inc. “History of the Lambs,” n.d. [https://the-lambs.org/history/](https://the-lambs.org/history/).

Young, Michelle. “On The Wall At Keens Steakhouse, A Blood-Stained Playbill Held By Abraham Lincoln When He Was Assassinated,” n.d. [https://untappedcities.com/2020/04/15/on-the-wall-at-keens-steakhouse-a-blood-stained-playbill-held-by-abraham-lincoln-when-he-was-assassinated/](https://untappedcities.com/2020/04/15/on-the-wall-at-keens-steakhouse-a-blood-stained-playbill-held-by-abraham-lincoln-when-he-was-assassinated/).
