---
title: "Chelsea Market"
author: "Abigail Tenenbaum"
---

Located near the piers lining the Hudson River, Chelsea Market is a retail and dining center that guarantees a good time spent. 

Decades before the Chelsea Market building housed the stores and offices that it does today, it was a factory for the National Biscuit Company (Nabisco). The building was built by the New York Biscuit Company, which was a group of local bakeries that came together in 1890 and built multiple bakery facilities along 10th Avenue. In 1898, the New York Biscuit Company combined with their Chicago-based competitor, the American Biscuit and Manufacturing Company, to create Nabisco. The so-called “Cracker Trust” expanded on these original facilities in the years to follow, adding more facilities until the baking complex took up a full city block. In the 1930s, Nabisco even changed the building structures to make way for a freight train that went through the building, allowing for direct train access. 

The building is in the heart of the Meatpacking District, which was known for its slaughterhouse and meat facilities. Nabisco even used the lard from the meat packers for their cookies. At first, Nabisco’s main product was the Uneeda Biscuit. The logo for the cookies, the Uneeda Biscuit Boy, still remains painted on the interior brick walls of Chelsea Market. The building is also where Nabisco tested and ultimately created the Oreo cookie, a popular biscuit to this day.  

In the 1950s, following the decline of the neighborhood, the Nabisco operations moved to New Jersey, where it was less expensive to hold facilities. That, alongside the more expansive space, had a lot of businesses and overall New York City residents move into the New Jersey suburbs. 

The building’s next owner was developer Irvin Cohen, who paid around 10 million dollars for the foreclosed mortgage.  At the time, the Meatpacking District was considered a sketchy neighborhood with little to no prospects, unsafe by all means. Cohen had hopes to create a food center, a dining hall with various restaurants for people to choose from freely.

Chelsea Market opened in 1997. On the ground floor opened a dining concourse, full of local businesses such as The Lobster Place that remain to this day. The dining hall model was majorly successful, helping drive tourism into Chelsea Market and the overall neighborhood. 

Today, the Meatpacking District is now one of the trendiest areas in New York City, full of clubs, high-end stores, and luxury condominiums. These additions to the neighborhood have led and contributed to gentrification, polishing away the rougher history of the area and replacing it with designer boutiques and salons. 

Chelsea Market attracts about 6 million visitors annually. The building was purchased by Alphabet (parent company of Google) in 2018 for 2.4 billion dollars. Google’s NYC headquarters sit across the street from Chelsea Market. The ground floor still holds the dining concourse, with various retail stores surrounding it. The basement floors also contain some restaurants, most which are local businesses, and opportunities to shop around. Chelsea Market also hosts a wide variety of events, from art installations to live music to fascinating workshops. With its rich history and landmark in the neighborhood, Chelsea Market has an undeniably immense contribution to its home in the Meatpacking District. 

Balkaran, Makesha. “The Meatpacking District - Living in the Shadow of Gentrification.” *Eportfolios@Macaulay*, May 4, 2019. [https://eportfolios.macaulay.cuny.edu/alonso2019/2019/05/04/the-meatpacking-district-living-in-the-shadow-of-gentrification/](https://eportfolios.macaulay.cuny.edu/alonso2019/2019/05/04/the-meatpacking-district-living-in-the-shadow-of-gentrification/).

Chelsea Market. “Our Story,” n.d. [https://www.chelseamarket.com/our-story](https://www.chelseamarket.com/our-story)

Martinelli, Katherine. “The Factory That Oreos Built.” *Smithsonian Magazine*, May 21, 2018. [https://www.smithsonianmag.com/history/factory-oreos-built-180969121/](https://www.smithsonianmag.com/history/factory-oreos-built-180969121/).

NYC: The Official Guide. “Meatpacking District,” n.d. [https://www.nycgo.com/boroughs-neighborhoods/manhattan/meatpacking-district/](https://www.nycgo.com/boroughs-neighborhoods/manhattan/meatpacking-district/).

Ottman, Jacquelyn. “Preserving the Historic Meatpacking District By Telling Its Stories.” *Chelsea News*, October 28, 2022. [https://www.chelseanewsny.com/news/preserving-the-historic-meatpacking-district-by-telling-its-stories-BB2254210](https://www.chelseanewsny.com/news/preserving-the-historic-meatpacking-district-by-telling-its-stories-BB2254210).

Rosenberg, Jennifer. “A History of the Oreo Cookie.” *ThoughtCo.*, September 13, 2019. [https://www.thoughtco.com/history-of-the-oreo-cookie-1779206](https://www.thoughtco.com/history-of-the-oreo-cookie-1779206).

Studios. “Chelsea Market,” n.d. [https://studios.com/chelsea-market.html](https://studios.com/chelsea-market.html).
