---
title: "Park Avenue"
author: "Kyi Williams"
---

Park Avenue is a world-renowned street in Manhattan, New York City. The avenue is home to some of the most luxurious and prestigious buildings, hotels, and businesses in New York. Park Avenue is split into four sections by the Grand Central Terminal, which serves as a major transportation hub for commuters in the city.
One of the most notable features of Park Avenue is the stunning array of architecture on display. The buildings along the avenue range from pre-war to modern, and the styles vary from neo-Gothic to Art Deco. One of the most iconic structures on the avenue is the MetLife Building, formerly known as the Pan Am Building. It is a prominent fixture on the New York City skyline and has been shown in countless movies and television shows. Another notable building is the Seagram Building, a modernist skyscraper designed by Ludwig Mies van der Rohe and Philip Johnson. Park Avenue is also home to many of the world's most luxurious hotels. The Waldorf Astoria, for example, is a legendary hotel that has hosted numerous celebrities and dignitaries over the years. The hotel's opulent design and grandeur have made it a favorite among the rich and famous. The St. Regis is another iconic hotel on Park Avenue known for its luxurious amenities and impeccable service.

However, the people who own places in this area are there for the purpose of gaining power. Not only do the people at the top gain political power using their wealth, but they also create a big gap between regular civilians. The people who own the expensive apartments own most of the capital of the U.S. The wealthy are considered the 1% and they overwhelm millions of people when it comes to income growth. Also, the wealth distribution in 2010 was 400 of the richest people equaled the income of 150 million people in the U.S. 

*Park Avenue: Money, Power and the American Dream⎜WHY POVERTY?⎜(Documentary)*. Accessed May 17, 2023. [https://www.youtube.com/watch?v=6niWzomA_So](https://www.youtube.com/watch?v=6niWzomA_So).

Friends of the Upper East Side. “Park Avenue Historic District.” Accessed May 17, 2023. [https://friends-ues.org/about/park-avenue-hd/](https://friends-ues.org/about/park-avenue-hd/).
