---
title: "Metropolitan Community Church New York (MCCNY)"
author: "Niamh Zanghi"
---

The Metropolitan Community Church of New York (MCCNY) is a Christian denomination that caters to and includes queer people in their ministry. The denomination was founded by Reverend Troy Perry in 1968 Los Angeles before expanding to NYC and other cities in the upcoming decade and, today, to thirty-seven countries.

Rev Perry founded the Metropolitan Community Church (MCC) with, according to MCC themselves, "A failed romance\[,\] An attempted suicide\[,\] A reconnection with God\[,\] An unexpected prophecy\[,\] And the birth of a dream." MCC began with small services and marches against anti-sodomy laws. In the early years, Rev Perry coordinated with many gay activists in Los Angeles, including (but not limited to) Morris Kight and Bob Humphries. MCC expanded to host the first post-Stonewall march in 1970. The group faced much opposition from Los Angeles police, with Rev Perry himself being beaten by them. But MCC continued and prevailed, spreading their mission and message across the nation. Recently, Rev Perry has been honored through a solo musical comedy in 2011, a tribute at Los Angeles Episcopal Cathedral in 2018, and the Dodgers Community Hero Lifetime Achievement Award in 2021.

Rev Perry's achievements were became widespread as the MCC grew in Los Angeles. A New York City branch quickly followed and became one of the church's most influential and successful branches.

MCCNY was founded in 1972, when it rented space from the Church of the Holy Apostles, led by Reverand Howard Wells. Since then, the church has lived in a 13th street building from 1983 to 1994, then in 446 West 36th street to today. Sylvia Rivera, a notable and highly influential transgender activist during the Stonewall era, was a member of MCCNY. She participated in the church's food pantry. To honor her, the church named their queer youth shelter Sylvia's Place. MCCNY campaigned for the Lesbian and Gay Community Center (today known as the LGBT Community Center) and for the general advancement of queer people. The church states their beliefs as:

*"God has created, loves, and includes every person as a unique and wonderful being in the commonwealth of God.*

*We are called to live out our faith through social justice and ministry within and beyond the church.*

*Prayer and worship are the focus of community life and the foundation of everything we do.*

*The purpose of queer people and our particular sexualities is to bring the world to right relationship.*

*We are intentionally called to create a spiritual home and safe haven that reflects the diversity of all God's people. Metropolitan Community Church of New York provides a spiritual home for the lesbian, gay, bisexual, and transgender community and for all who choose to join us through the practicing of the gospel of Jesus Christ in worship, prayer, social action, education, and fellowship so that all people might experience God's liberating love, wholeness, and justice; come to live in right relationship with God and all creation; and have the courage to change the world."*

MCCNY has done much for the queer community since its entrance to New York City. They offer community dinners, a spirituality group for transgender and genderqueer people, a Sunday school for children, a free LGBTQ health clinic, and much more. They have engaging weekly services, with the music ministry performing traditional worship songs and pop songs, such as P!NK's "Hurts 2B Human."

Sources

1.  [MCCNY Offical Website](http://www.mccny.org/index.htm)

2.  [Metropolitan Community Church of New York - NYC LGBT Historic Sites Project](https://www.nyclgbtsites.org/site/metropolitan-community-church-of-new-york/)

3.  [How Troy Perry, Metropolitan Community Church Founder, Made LGBTQ History-- With God's Help - Tim Teeman - Jan 26, 2021](https://www.thedailybeast.com/how-troy-perry-metropolitan-community-church-founder-made-lgbtq-history-with-gods-help)

4.  [Pride in Pictures 2000: Silvia Rivera & our transgender leaders - Ron Johnson - June 14, 2018](https://www.lgbtqnation.com/2018/06/pride-pictures-2000-sylvia-rivera-transgender-leaders/)

5.  [The MCCNY choir Singing "Hurts 2B Human" by P!NK during the 11am Celebration Service - Metropolitan Community Church of New York - April 5, 2023](https://www.youtube.com/watch?v=o5pJD3OKbKY)

6.  [Troy Perry - Wikipedia](https://en.wikipedia.org/wiki/Troy_Perry#Personal_life)
