---
author: "Warren Marburg"
title: "Taverna Kyclades"
---

The neighborhood of Astoria, Queens has had many waves of immigration. The very first settlers who arrived in the early 17th century were Dutch, living alongside the indigenous people for a time. By the time of the mid-17th century, the English settlers arrived, who bought most of the land in Queens. When the 19th century came, long after the revolutionary war, Astoria became home to Manhattan elite. They used the space to build large houses. Stephen Halsey, a fur merchant, officially founded what was then called Hallett’s Cove in 1839. He later petitioned to rename the neighborhood Astoria after America's first multi-millionaire, John Jacob Astor. The mid-19th century saw a wave of German and Irish immigrants. In the 20th century, after World War II, Astoria had a wave of immigrants from Italy and Greece. Greeks started to make up a significant part of Astoria’s population, as they represented approximately half by the mid-90s. The diversity in the neighborhood includes immigrants from all over the world today. In terms of cuisine, however, Astoria is thought of as the “go-to neighborhood” for Greek food.

On Ditmars Boulevard, there stands a Greek restaurant that has reached fame beyond a local legacy. Taverna Kyclades is a family owned restaurant that serves Greek seafood dishes. Their staff are even dressed in White and Blue to match the colors of the Greek flag. Their website claims their octopus and calamari are especially popular. This Astoria landmark is named after a group of islands in Greece called Kyclades. As a family business, they like to treat their customers as if they were family.

Frank Bruni of The New York Times said that prior to eating at Taverna Kyclades, he heard several recommendations that included certain menu items. Some of which were the Taramosalata and Octopus. There was even a mention of fried cheese, which Bruni was less thrilled about. That is until he tried it, however, and he liked it. The octopus in particular is the major attraction, as they are a seafood restaurant. Other menu items that can be found include stuffed clams, spicy feta dip, and fried calamari. Kyclades doesn’t take reservations, which means that wait times for a table can be long especially due its popularity.

The popularity of Kyclades has reached people from all neighborhoods and cultures in New York City to try its authentic Greek cuisine. The restaurant has expanded two more locations: Manhattan’s East village in 2013; and Bayside, Queens in 2017. Taverna Kyclades’ owner, Adrian Skenderi, was joined by the top chefs in NYC for the Chefs' Tribute to Citymeals on Wheels, a culinary fundraiser to bring meals to New Yorkers in need. According to Skenderi, "We all need to recognize that we must help and give back to our community." He continued, “While some of us were able to get to a place of peace and comfort, there are others that just need a little help to reach that place as well.” The City Meals on Wheels program serves around 2 million meals each year.

Sources:

https://www.tavernakyclades.com/about-us

https://theculturetrip.com/north-america/usa/new-york/articles/a-brief-history-of-astoria-queens/

https://patch.com/new-york/bayside/taverna-kyclades-owner-reps-bayside-star-studded-fundraiser

https://archive.nytimes.com/dinersjournal.blogs.nytimes.com/2009/04/20/out-and-about-taverna-kyclades/

https://qns.com/2017/12/popular-greek-restaurant-taverna-kyclades-prepares-open-baysides-bell-boulevard-location/

https://ny.eater.com/2013/8/20/6384639/astoria-hit-taverna-kyclades-expands-to-the-east-village