---
title: "Corona Youth Music Project"
author: "Christopher Soto"
---

The Corona Youth Music Project (CYMP) is a remarkable music education program available to all the young buds of Corona, NY. Founded in 2010, CYMP, is determined to “promote social inclusion in New York City by empowering youth and children in Corona, Queens to excel through their participation in musical ensembles” ([nucleocorona.org](http://nucleocorona.org/) About tab). 

Corona, Queens is a multicultural neighborhood. The area is home to many members of the Latin American community. Corona's diversity is shown through the different foods, language, accents, clothing, practices, and customs that are publicly expressed. Although the area may not be the most pleasant to walk through, Corona's vibrancy is maintained through its multicultural backgrounds and icons. Such icons include Citi Field, flushing meadows park, and home of a very influential jazz legend, Louis Armstrong.   

The Corona Youth Music project is the first in Queens inspired by “El Sistema”, “a global movement of social action through music” ([nucleocorona.org](http://nucleocorona.org/) El Sistema tab). El Sistema began in Venezuela in 1975 by José Maestro Abreu. He was determined to give the children of underserved communities the education to participate in orchestras and choirs; and believed that with their instruments his students will change the world ([nucleocorona.org](http://nucleocorona.org/) El Sistema tab). His influence spread around Venezuela, followed by the rest of Latin America, and later the whole world. 

The Corona Youth Music project is a free music education program as well as a safe and fun place for the community. CYMP has three orchestras; No Frontiers, a beginning level ensemble, Corona Children's Orchestra, and Corona Youth Orchestra. Within the program, students build a strong community bond. Students practice teamwork, inspire each other, and mentor the young participants of the community as well as each other.   

The program showcases the students growth and accomplishments through joyful and energetic performances that are open to the local community and the rest of NYC for free! For example, each year during the holiday season CYMP holds a showcase where students perform music that spells out the holiday spirt. Such classical pieces include, A Christmas festival, Rudolf the Red Nose Reindeer, Sleigh Ride, Christmas in the kitchen, and much more. Students also perform famous pieces such as those of Beethoven, Georges Bizet, Franz Schubert, Leroy Anderson, and many more. 

Today the Corona Youth Music Project holds its ensembles in P.S 19 Q, one of the largest and oldest public school in the city, and welcomes in new members each year.

**SUB TOPIC**

UPBeat NYC is another program inspired by “El Sistema” in the Bronx. There are many instance where UPBeat NYC collaborates with the Corona Youth Music project, and the result is a spectacular! breathtaking! performance by both programs.  

P.S 19 Q is a public elementary school in Corona, Queens. Being a school since 1923, the school continues to expand and maintain its doors open to all incoming students.  

**ANNOTATED BIBLIOGRAPHY**

Núñez, Álvaro F. Rodas. “Acción Social Por La Música:‘El Sistema’ En Nueva York.” *Periférica Internacional. Revista Para El Análisis de La Cultura y El Territorio*, no. 16, 2015, pp. 155–64.

*Home*. [http://www.nucleocorona.org/Corona_Youth_Music_Project/Home.html](http://www.nucleocorona.org/Corona_Youth_Music_Project/Home.html). Accessed 20 Apr. 2023.

*CORONA YOUTH MUSIC PROJECT INC | Benevity Causes*. [https://causes.benevity.org/causes/840-454330826](https://causes.benevity.org/causes/840-454330826). Accessed 20 Apr. 2023.

*Corona Youth Music Project*. [https://www.idealist.org/en/nonprofit/db1e2c7407b34aebbce7f271885641e8-corona-youth-music-project-new-york-city](https://www.idealist.org/en/nonprofit/db1e2c7407b34aebbce7f271885641e8-corona-youth-music-project-new-york-city). Accessed 20 Apr. 2023.

Museum, Queens. “Queens Museum | Corona Youth Music Project.” *Queens Museum | Corona Youth Music Project*, [https://queensmuseum.org](https://queensmuseum.org/). Accessed 20 Apr. 2023.
