---
author: "Carina Alessandro"
title: "Closed NYC Train Stations"
date: "5/11/23"
---

Before the Metropolitan Transportation Authority, NYC’s transportation was run by three private corporations: the IRT (Interborough Transit Company), the BMT (Brooklyn-Manhattan Transit Corporation) and the IND (Independent Subway System, confusingly). They are part of the reason why there’s so many closed train stations in the city: they became consolidated and run by the city and many routes even became redundant, as they didn’t have to compete with each other at that point. Much of those were demolished to be unusable or simply abandoned and left intact if they didn’t physically hinder the creation of new routes. Those that were demolished for redundancy were mostly elevated lines that had matched routes in underground lines.
The rest of the closed stations were usually shuttered because they were close to another station, but some were closed by rare circumstances. 

One notable station closed due to proximity to other stations was the Court Street Station in Brooklyn, which served as part of the IND’s Fulton Street Line. Being close to other stations in Downtown Brooklyn (which lead to other factors like low ridership and finding transfers obsolete), Court Street Station was abandoned in 1946 ten years after its opening. The soiled walls led the New York City Transit Authority to test a new cleaning method on them in 1960, and sixteen years later this station became home to the New York City Transit Exhibit. Containing preserved subway artifacts, the museum is still open today (now run by the MTA) despite it being planned on closing a year after opening, in 1977.

Significant rare circumstances have been present in multiple train station closings. One train station lasted only for a year, and was purpose built for a specific event: the 1939 World Fair. The IND built the Queens station to move people more easily to the fair, but it wasn’t popular since the fare was an extra 5¢, and was demolished when dismantled, not to be reopened in the 1964 Fair. One station that closed and then reopened, though, was the IRT’s Intervale Avenue Station in the Bronx. After a failed robbery of the South Bronx Subway token booth ended in an arson in 1989 (which imitated a previous token robbery in a Brooklyn station, but didn’t kill the clerk), the station was closed until it finished vigorous reconstruction in 1992.

Another even more unfortunate event was responded with a train station closure and reopening as well. The IRT’s WTC Cortland Station in Manhattan was under ground zero of the September 11th attacks, and was rebuilt and opened in 2018. However, BMT’s Cortlandt Street Station, which also sustained damage, was closed and rebuilt for a year after 2001, reopened, but then again permanently to make way for the building of Dey Street Passageway and the rebuilding of the World Trade Station.

## Sources

Brennan, Joseph. Abandoned Stations, Columbia University, https://www.columbia.edu/~brennan/abandoned/index.html.

Fermino, Jennifer. “G. Zero Station Set to Reopen.” New York Post, New York Post, 3 Aug. 2011, https://nypost.com/2011/08/03/g-zero-station-set-to-reopen/.

“IND Subway Line to 1939 World’s Fair.” Queens Chronicle, 3 Nov. 2022, https://www.qchron.com/qboro/i_have_often_walked/ind-subway-line-to-world-s-fair/article_a3f7168e-a2c7-51b9-89d5-293c1630ae5d.html.

“IRT Station to Take 2&nbsp;1/2 Years.” The New York Times, The New York Times, 17 Mar. 1990, https://www.nytimes.com/1990/03/17/nyregion/irt-station-to-take-2-1-2-years.html.

“Learn about the New York Transit Museum: New York Spaces.” New York Spaces | Covering All Thinks New York!, 16 Sept. 2022, https://newyorkspaces.com/learn-about-the-new-york-transit-museum/.

“Sources: 1 Train Stop Closed since 9/11 to Reopen Saturday.” Sources: Long-Awaited 1 Train Stop Will Reopen Saturday,

https://www.ny1.com/nyc/all-boroughs/transit/2018/09/07/cortland-street-station-to-reopen-soon-after-17-years-manhattan-nyc-train-station-sto
