---
title: "Affordable Housing "
author: "Vanessa Cruz"
---

The past is very much with us in New York’s Housing Landscape. 

Beginning in the 1820’s and 1830’s, early row houses modeled after English terraces were built to house people who could live where land costs were high, like artisans. Apartment houses only became built a century later, in the 1920’s. Row houses provided what many single family homes have today but at a lower cost. Residents were given privacy, yards and equity. Between 1860 and 1910, tenements were built due to increasing numbers of immigrants coming from Europe with little to no money. By 1900, over half of the 3 million people home to New York City, lived in these low sanitary tenements that were modeled after row houses. Due to the tenements being modeled after row houses, the living conditions or lack thereof, caused rates of disease and morality to soar. *The same model of a 25 x 100 foot lot that was originally meant to house 1 to 4 people, was now being used to house 80 to 150 people.* They increased the height of the row house to five or six stories, rather than two, three and four stories, like in the original model. Still, there was little air in the rooms and a lack of plumbing. In 1887 and 1889, A.T White (a Brooklyn businessman) constructed apartments that were modeled after London’s philanthropic housing developments. His Home Buildings and then Tower Buildings in Cobble Hill were meant to house the steadily employed, working class family. In light of this, most developers did not accept his projects as models for mass construction of low income housing. However, after some model development, the row house became and remains a popular choice for moderate income families to live in. Yet, not everyone can afford these houses.

One solution proposed to combat housing issues in NYC was brought up by Mayor Koch in the 1980’s and focused on neighborhood revitalization. It suggested a 10 year plan that invested $5.1 billion dollars into constructing or rehabilitating more than 180,000 units of housing in various NYC neighborhoods. The 10 year plan targeted extremely depressed neighborhoods that were in desperate need of revitalization. Over 50% of all housing units built and revitalized during the 10 year plan were located in districts of the South Bronx, Harlem, and Central Brooklyn. Besides this, Mayor Koch also adjusted the shelter systems to use barrack-style dormitories instead of comfortable, hotel-like placements. The logic behind this change was that it would let NYC officials differentiate people who depended on housing from those who only wanted a free home but could afford something better. Overall, his solution granted an era of prosperity for New York residents, but it did not last for long. 

Fast Forward to 2014, Mayor De Blasio came up with another solution for inaffordable housing. The same vacant lots that had been used for housing development in the 1920’s and so forth by A.T White and other builders, were now being sold to non-profit and for profit developers across the 5 burroughs. In association with 596 acres, a non-profit organization which advocates for the transformation of vacant lots into areas of green spaces and for civic engagement, De Blasio is selling these lots so they can build community. The vacant lots, now being sold as One Dollar Lots, were most prominently in the Bronx and Brooklyn. The Bronx continues to be a burrough that has been neglected and its people - forgotten to be taken care of. 

To combat this neglec, Housing Court in the Bronx is a group of people who are fighting eviction and insufferable living conditions. There is a surplus of rodents and roaches, all while there is a continuous rising interest in housing. Although this is an issue most concentrated in the Bronx, it is an issue across all 5 boroughs. In August 2022, average rent in Manhattan went up to $5,246 from $4,094. That is a 28% increase. In 2010, the Department of City Planning estimated that by 2030, NYC would have a population of 8.8 million people, yet NYC has reached that number almost 10 years earlier, which means housing production is very far behind. Residents are low-income and cannot afford rent. People who want to move here have nowhere to live. According to the New York City Housing and Vacancy Survey, apartments renting for between $801 and $1,499 is just 0.9%. Where are people who cannot afford beyond this number supposed to live?

The current solution proposed by Mayor Adams in 2022 is the “Get Stuff Built” solution. He has the goal to produce over 500,000 new homes over the next decade. He wishes to partner with New York State, the New York City Council, and New Yorkers in all five boroughs to complete this. He also wants to lower the cost of development by accelerating project timelines by 50%. His goal is to be efficient and to create affordable housing. The three points he presents are to Build Faster, Build everywhere, and Build together. Prohibiting exclusionary zoning practices, speeding up the pre-certification process, and reducing or eliminating unnecessary parking requirements that add cost and reduce the number of homes being built are just some of the steps he plans to take. 

Unaffordable housing has made New York almost unlivable. Perhaps that’ll finally change. 

Frishberg, Hannah. “New Map Shows Every City-Owned Lot Sold for $1 since de Blasio Became Mayor.” Curbed NY, March 13, 2018. [https://ny.curbed.com/2018/3/13/17115052/new-york-city-owned-land-lots-interactive-map](https://ny.curbed.com/2018/3/13/17115052/new-york-city-owned-land-lots-interactive-map).

Gardner, Deborah. “Notes on New York’s Housing History.” The Architectural League of New York, February 28, 2018. [https://archleague.org/article/new-york-housing/](https://archleague.org/article/new-york-housing/).

“Mayor Adams Unveils ‘Get Stuff Built,’ Bold Three-Pronged Strategy to Tackle Affordable Housing Crisis, Sets ‘Moonshot’ Goal of 500,000 New Homes.” The official website of the City of New York, December 8, 2022. [https://www.nyc.gov/office-of-the-mayor/news/893-22/mayor-adams-get-stuff-built-bold-three-pronged-strategy-tackle-affordable-housing#/0](https://www.nyc.gov/office-of-the-mayor/news/893-22/mayor-adams-get-stuff-built-bold-three-pronged-strategy-tackle-affordable-housing#/0).

Ngo, Emily. “In New York City, Housing Supply Continues to Fail to Meet Demand.” In New York City, housing supply fails to meet demand, October 10, 2022. [https://www.ny1.com/nyc/all-boroughs/housing/2022/10/07/new-york-city-housing-supply-demand](https://www.ny1.com/nyc/all-boroughs/housing/2022/10/07/new-york-city-housing-supply-demand).

Schill, Michael H., Ingrid Gould Ellen, Amy Ellen Schwartz, and Ioan Voicu. Revitalizing inner-city neighborhoods: New York City’s ten-Year plan, 2002. [https://furmancenter.org/files/publications/Revitalizing_Inner_City_Neighborhoods.pdf](https://furmancenter.org/files/publications/Revitalizing_Inner_City_Neighborhoods.pdf).