---
title: "R211 Trains"
author: "Vanessa Cruz"
---

In the 19th century, NYC began to expand into the “The Big Apple” we know today. With an influx of European immigrants and a bustling city, engineers looked to an undergound solution that could sustain quick and efficient transportation; more effective than horse-drawn carriages and better than elevated trains pulled by steam locomotives above ground. The city’s first subway opened in 1870 and was a short underground tunnel measuring 312 feet beneath Broadway that stretched from Warren Street to Murray street, near City Hall. The first train was an eight foot long car that in theory, could carry 18 passengers and was mobilized by 100 horsepower. Although it was an impressive engineering feat, it was left as a short-lived public demonstration. Due to the **Panic of 1873**, a stock market crash in Europe that affected European’s investments of American railroads, the first subway of 1870 was a project that could no longer be supported. In 1897 however, the Treemont Street Subway in Boston was the first subway in the United States. This streetcar line inspired New York City to re-begin construction on their rapid transit system. The first subway line opened on October 27th, 1904 and had four tracks with express stations located approximately 1.5 miles apart at Brooklyn Bridge, 14th Street, Grand Central, 72nd Street, and 96th Street, with local stations spread apart about a quarter of a mile away from eachother. The ASCE’s Board of Directors voted in 1977 to declare NYC’s first subway as a National Historic Civil Engineering landmark. Yes, NYC’s subway was an incredibly impressive and unique engineering accomplishment. However, what engineers failed to take into consideration when building these efficient and comfortable modes of transportation, was the safety of its passengers. 

Although the engineers managed to make efficient train systems, they focused more on the engineering aspects of the railways and less on the makeup of each train car. This is something that would cause problems, even today. The New York Times wrote that there was a 22 per cent increase in crime in 2022 compared to 2021. A lot of these crimes occur on the subway. According to the Gothamist, a non-profit newsroom, grand larcenies plummeted in 2020, early in the pandemic. This was due to there being less subway riders, which meant less phones to steal and people to corner. However, now that there are more people returning to NYC’s subways, crime rates are continuing to rise again. To combat this, Mayor Eric Adams and Gov. Kathy Hochul have ordered an additional 1200 NYC officers to patrol the train stations. However, there still needs to be a solution for riders safety within the train cars. An MTA survery from August 2022 found that only 54 per cent of riders felt safe on trains and nearly 70 per cent felt that there were not enough police in the subway system. Due to a lack of safety, there has been a decrease in subway riders, even though numbers are beginning to climb again. The MTA hopes to reach 1.3 billion riders a year in 2026. In 2015 however, there were 1.8 billion riders a year. 

The first step NYC can take to increase the number of subway riders again is to improve the train system. The new R211 trains are the first new subway cars to join the city’s train car system in five years. The MTA is investing over 6 billion dollars. The R211 cars will first be put on the A line and will feature wider doors that are 58 inches wide, compared to the previous 50 inch doors. This is supposed to reduce station stop times by 32 per cent. There have been 1,200 new R211 cars ordered, which costed nearly $3.2 billion dollars. Besides wider doors, the new trains will also feature open gateways to allow passengers to easily move between each car; something that is common on major European subways like London and Paris. The cars will also have cameras inside to increase public safety, alongside the police officers that Mayor Adams ordered to patrol the stations. 

Bascome, Erik. “MTA Hosts Inaugural Ride on Brand New R211 Subway Cars.” silive, March 10, 2023. [https://www.silive.com/news/2023/03/mta-hosts-inaugural-ride-on-brand-new-r211-subway-cars.html](https://www.silive.com/news/2023/03/mta-hosts-inaugural-ride-on-brand-new-r211-subway-cars.html).

“Committees.” ASCE Metropolitan Section. Accessed May 17, 2023. [https://www.ascemetsection.org/committees/history-and-heritage/landmarks/first-new-york-city-subway](https://www.ascemetsection.org/committees/history-and-heritage/landmarks/first-new-york-city-subway).

Hicks, Nolan. “MTA Unveils New Sleek, High-Tech Subway Cars - Here’s What Lines Are Getting Them.” New York Post, February 4, 2023. [https://nypost.com/2023/02/03/mta-unveils-new-nyc-subway-cars-for-a-c-line-riders/](https://nypost.com/2023/02/03/mta-unveils-new-nyc-subway-cars-for-a-c-line-riders/).

Marcius, Chelsia Rose, and Ed Shanahan. “Major Crimes Rose 22 Percent in New York City, Even as Shootings Fell.” The New York Times, January 6, 2023. [https://www.nytimes.com/2023/01/05/nyregion/new-york-crime-stats.html](https://www.nytimes.com/2023/01/05/nyregion/new-york-crime-stats.html).

Stephen Nessen. “Subway Safety Is an Election Issue and Problem for the MTA’s Finances. but Just How Dangerous Is It to Ride the Rails?” Gothamist. Accessed May 17, 2023. [https://gothamist.com/news/subway-safety-is-an-election-issue-and-problem-for-mtas-finances-but-just-how-dangerous-is-it-to-ride-the-rails](https://gothamist.com/news/subway-safety-is-an-election-issue-and-problem-for-mtas-finances-but-just-how-dangerous-is-it-to-ride-the-rails).