---
author: "Martina Garcia"
title: "Women in Need"
date: "5/11/23"
---

Who are Women in Need? Well, this organization started in 1983 when a group of women that decided to call themselves "*Women in Need"*open a shelter for four woman and their kids, with the help of the Church of St. Mary.After realizing the needs that many women had around that time Win decided to open another shelter, but this time in Brooklyn called"*Monica House*", three years after they open another homeless house in the Bronx called Casa Rita for 16 families. In 1987 Win opened Alexander Abraham Residence for 31 families also in Manhattan and two other home shelter in the Bronx in 1989. Win is the largest shelter giver. You might be asking yourself, what do they do? Or how many people they have helped? Something interesting about this organization is that Win has fourth teen shelters around the borough that provide house to more than 1000 women in need and their Childs every day. This website illustrates, "4,800 people are houses by WIN, each night including over 2700 children". This shows this shows that the organization contains a wide range of homeless people helpers that offer a better life to all these women and their families. Among the services provided are case management, support, and long-term residential housing. Case managers who deal with clients make house calls and have regular office hours. Case management services can also include crisis intervention, job training and workforce readiness counseling, education counseling, assistance with budgeting and other financial literacy skills, and referrals to programs for physical and/or mental health difficulties, depending on the client.

Additionally, Win is also recognized because they offer traditional and temporary houses for the homeless women they attend.*"ClearPath"*demonstrates that, "nearly 10% of homeless families in New York City are housed by WIN." This only shows that Win gives homeless families in New York City the comprehensive support they need to thrive on their own, including safe homes, vital resources, and ground-breaking initiatives. As a result, these families reclaim their independence, and their children may look forward to a better future. NYC DHS expresses that, The Housing Assistance Program, an anti-eviction initiative aimed at a high-risk zip code in the Bronx, was developed and implemented with Win's help as a significant partner in recent years. This involvement with DHS's homelessness prevention initiatives has increased. This demonstrates that they not only work alone to improve the community, but also collaborate with other organizations to make their impact better. To end the cycle of homelessness and shorten the time that people spend living in shelters, Win is advocating for changes that will assist New York families in finding and maintaining permanent homes. The thousands of families and kids who are experiencing homelessness will have more housing stability thanks to these actions, which will significantly reduce instability and enhance outcomes. By updating the city's Family Intake procedure and establishing a shelter development fund for reputable charity providers, you can make sure that families in need may get the resources they need for refuge. Increase the quantity of rental aid vouchers available to families and enforce the fair housing legislation. Provide families the resources they need to keep a permanent home, such as childcare subsidies, 18 months of aftercare, and routes to respectable work.

## Work Cited

*Women's Organization \| WiN*.<http://www.winnrcs.org/about-us>. Accessed 29 Mar. 2023.

"WinNYC."*WIN*,<https://winnyc.org/>. Accessed 29 Mar. 2023.

*Win - DHS*.<https://www.nyc.gov/site/dhs/about/win.page>. Accessed 29 Mar. 2023.

"NYC Organizations That Help Women in Need."*ClearPathNYC*,<https://www.clearpathnyc.org/blog/nyc-organizations-help-women>. Accessed 29 Mar. 2023.

"Supportive Housing - Women In Need Inc. (Win) Serving Brooklyn, NY."*Findhelp.Org*,[https://www.findhelp.org/women-in-need-inc.-%2528win%2529--new-york-ny--permanent-home/5082032239542272?postal=11218](https://www.findhelp.org/women-in-need-inc.-%2528win%2529--new-york-ny--permanent-home/5082032239542272?postal=11218). Accessed 29 Mar. 2023.
