---
author: "Martina Garcia"
title: "The Life of Street Vendors"
date: "5/11/23"
---

The Life of Street Vendors

Street vendors risk their lives everyday to support their families in the country and even to send money outside the US. Street vendors work hard long hours just to earn the minimum wage. Beside all this, street vendors go through police brutality, injustice and their rights are barely existing. According to the Guardian, “Cops slap vendors with tickets that can eat up half their take-home pay.” This quote suggests that some officers take advantage of their power to ruin the life of the least fortunate people, especially the illegal community. A lot of the street vendors are illegal, and their only source is selling clothes, food, and other items in the streets. However, how can their success be possible if their fear of getting a ticket that can cost them 8+ hours of work, assaulted by a police officer or even arrested is bigger than their dream to be better. 

Street vendors went to the pressure of watching what they do and how they do it due to the extreme rules they had to follow. Again from the guardian, “In 2015, the city’s environmental control board wrote 18,744 vending violation tickets.” This quote illustrates that the smallest mistake a street vendor made could have cost them half of their wage. Nonetheless, people such as Osama Khatlan who wore a cape of tickets with offenses and ridiculous reasons, helped to protest and protect the rights of himself and the other street workers. In addition,  Khatlan addressed a diverse audience, including a West African handbag vendor, a Chinese street artist, a Latina vendor and a few organizers. They moved toward downtown to the cries of "vendor power!" and the wave of flags. Nevertheless, the fight for these rights doesn’t stop there.

The City Council approved a law in 2021 that increased the availability of food vendor permits, created an office of street vendor enforcement, and formed a street vendor advisory board in July last year.  *NYC food policy* illustrates, “the number of food street vending licenses will be raised every year for the following ten, through 2032, by 445. The overall number of available units will ultimately double as a result.” This demonstrates that futures vendors are able to obtain a peaceful way to a successful business. Although the fights against these injustices are showing good results, the fight is not over. The number of Mobile Food Vending Permits that may be issued to food trucks and carts is capped by City legislation, but the number of Mobile Food Vending Licenses is not constrained. Long waitlists for permits (some of which have been closed for more than a decade) and an unofficial black market for permits emerge from this. Some vendors have paid a permit holder up to $20,000 to illegitimately sublease them. To finalize, the smallest enterprises in New York State, street vendors play a crucial role in the economy and cultural landscape of New York City. Around 20,000 business owners, mostly immigrants, people of color, veterans, and women, work as street vendors. Many of them are part of a shadow economy made up of people who are unable to obtain the business licenses they need to legally operate their company. 

## Work Cited

*Street Vendor Salary in New York ‐ CareerExplorer*. [https://www.careerexplorer.com/careers/street-vendor/salary/new-york/](https://www.careerexplorer.com/careers/street-vendor/salary/new-york/). Accessed 26 Apr. 2023.

*What Life Is Like for Immigrant New York Street Vendors | Civil Eats*. [https://civileats.com/2020/10/02/what-life-is-like-for-immigrant-new-york-street-vendors/](https://civileats.com/2020/10/02/what-life-is-like-for-immigrant-new-york-street-vendors/). Accessed 26 Apr. 2023.

Butz, Leah. “The Status of Street Vendors in NYC: Background and Overview.” *NYC Food Policy Center (Hunter College)*, 23 May 2022, [https://www.nycfoodpolicy.org/the-status-of-street-vendors-in-nyc-background-and-overview/](https://www.nycfoodpolicy.org/the-status-of-street-vendors-in-nyc-background-and-overview/).

[http://www.wiego.org/sites/default/files/resources/files/United-States-of-America-Street-Vending-Regulations-in-New-York-City-An-Overview.pdf](http://www.wiego.org/sites/default/files/resources/files/United-States-of-America-Street-Vending-Regulations-in-New-York-City-An-Overview.pdf)
