---
author: "Warren Marburg"
title: "Randall's Island"
---

Randalls and Wards Islands, also known as Randall's Island, are fascinating conjoined islands that provide tremendous benefits to our congested city. It consists mainly of luscious parkland. The island is widely accessible to Manhattanites across the Harlem River; Queens residents via the East River; and those from the Bronx by way of the Bronx Kill Strait. This 520 acre land has convenient access from these three boroughs via bridges and offers a variety of activities. Activities available on the island include music and cherry blossom festivals, movies, tours, nature walks, biking, and yoga. Facilities consist of 91 athletic fields, a golf course, batting cages, a tennis center, an urban farm, a track and field stadium, playgrounds, picnic grounds, and eight miles of waterfront pedestrian/bike trails, wetlands, and a saltmarsh.

What makes Randall's Island especially unique is the ability for a pedestrian or biker to easily travel through three different boroughs without ever setting foot in a car. This is possible with the help of the Triborough Bridge connecting Astoria; the Wards Island Bridge adjoining East Harlem; and the Randall’s Island Connector linking the South Bronx to Randall's Island.

In addition to offering a place of leisure for all New Yorkers, Randall's Island is also currently home to two psychiatric centers, a drug and alcohol treatment facility, a daycare center, two state police stations, a Fire Department Academy, a DEP treatment plant, three homeless shelters for men, and an employment center. There is presently no residential housing on the island.

Originally named Minnehanonck and Tenkenas, meaning "wildlands," by indigenous inhabitants, this land was purchased by the Dutch in 1637. It was subsequently bought by a British Army engineer in 1772, who lived there with his wife until it was used as a British army base, with the goal of strategically attacking Manhattan during the American Revolution. Because the British were defeated, Jonathan Randall, as well as Jasper and Bartholomew Ward were able to purchase the land in 1784. The Ward brothers abandoned the land in 1840 after the first bridge was destroyed in a storm, and in 1835, Randall's heirs sold the island to the city for $60,000. This municipality was then primarily used to house social facilities such as orphanages, poor houses, burial grounds, immigrant hospitals, and insane asylums. After the Triborough Bridge was built in 1936, allowing for more accessibility. the island slowly began to transform into parkland. In addition, in 1960, the land between Ward and Randal Islands was filled in for the purposes of land expansion, officially connecting the two islands.

In recent years, great media attention was paid to Randall’s Island as Mayor Adams decided to build a 84,000 square foot shelter for housing 500 male migrants in October 2022. Unfortunately there were conflicting opinions regarding the safety and comfort of the shelter, and it was subsequently closed down one month later.

Sources:
https://www.nycgovparks.org/parks/randalls-island/highlights/6515https://www.atlasobscura.com/articles/islands-of-the-undesirables-randall-s-island-and-wards-islandhttps://www.nytimes.com/2022/11/10/nyregion/migrant-shelter-randalls-island-close.htmlhttps://www.nytimes.com/2022/10/18/nyregion/migrant-tents-randalls-island.html