---
title: "Mayor’s Office of Community Mental Health"
author: "Lucca O'Connor"
---

In the wake of an international pandemic that shut down the entire country, a lot of mental health issues began to arise. While necessary to keep people from getting sick, the several years of isolation from quarantine created a negative impact on people’s mental health. To address the impact that the pandemic quarantine had on people, the New York City Council established the Mayor’s Office of Community Mental Health back in December of 2021. Amending the City Charter, the new service would work towards progress in helping New Yorkers dealing with mental health issues.

Since his induction into serving in 2022, New York City Mayor Eric Adams released an agenda to further the support for mental health. His agenda, “Care, Community, Action: A Mental Health Plan for New York City”, would further support resources that aid in mental health. This includes programs for youth suicide or launching telehealth programs for high school students. The program also aims towards overdose prevention, hoping to reduce overdose deaths fifteen percent by the year 2025. The agenda’s final goal is for serious mental illness treatment, and would allow greater connections to facilities that aid in that department. Mayor Adams plans on investing $20 million towards this program

Another plan of Mayor Adam’s to address mental health issues is to give aid to people whose mental health issues are not being cared for. From NYC Mayor’s Office of Community Mental Health’s website:

“Measures in Mayor Adams’ legislative agenda announced today include:

- Making the law explicit that a person requires care when their mental illness prevents them from meeting their own basic needs;
- Mandating that hospital clinicians consider a range of factors when assessing a patient’s need for involuntary admission or retention, including known treatment history and current ability to adhere to outpatient treatment;
- Requiring hospitals to screen all psychiatric patients prior to discharge for their need to receive “assisted outpatient treatment” (court-ordered care under “Kendra’s Law”);
- Allowing a broader range of trained mental health professionals to perform evaluations and community removals of individuals in crisis; and
- Requiring hospitals to notify known community providers when their clients are admitted or released and collaborate with community providers in preparing patients for discharge.”

This measure would be applied citywide, so while it was announced at a meeting in Albany, it would still impact New Yorkers within the five boroughs.  The biggest concern these plans bring up is that police would be given too much control over people.  They would be able to forcibly move people they deem mentally unwell into the places created by these programs.  In particular, homeless people face frequent harassment from the police, and these policies enable this further.

The impact that the pandemic had on the general mental health of the people cannot be understated. But New Yorkers are working for ways to improve these conditions for the better.

Sources: 

[Policies and Practices to Support Undergraduate Teaching Improvement | American Academy of Arts and Sciences](https://www.amacad.org/publication/policies-and-practices-support-undergraduate-teaching-improvement/section/6)

[](https://onenyc.cityofnewyork.us/wp-content/uploads/2019/05/OneNYC-2050-Equity-and-Excellence-in-Education.pdf)

[Every Student Succeeds Act (ESSA)](https://www.nysed.gov/essa)
