---
author: "Nicole Roytlender"
title: "Outdoor time"
---

The big city lifestyle, while providing abundant opportunities in other aspects, frequently falls short in encouraging time spent outdoors and in nature as well as overall exercise and physical health. Adults who are conscious of the benefits of getting outside and off the screens have difficulty making it a priority, let alone children who don't necessarily know its significance yet. As someone who has attended public school in two different states, the difference in physical curriculum is evidently stark. As early as elementary school in southern California, we had ample daily recess, which granted us access to not only a playground, but a track, and a field. Sports were encouraged by providing basketballs, soccer balls, kickballs, etc. as well as a tether ball area. Not only that, but every morning before school would begin, we were given access to the track to run laps, with incentives including various prizes for running set amounts over time. To add, most schools had gardens outdoors with fresh fruits and vegetables, all student grown and maintained. Other activities such as occasionally marathons and outdoor fairs were frequent and amounted to a great deal of participation not only on behalf of students and faculty, but parents and families as well. Although this all seemed ”normal” and day-to-day at the time, it was not until moving to Brooklyn, New York that it became apparent that not all students are fortunate to have these opportunities. Granted the lack of outdoor space in NYC is not as readily available, it is that much more crucial that an effort be out forth to encourage outdoor recreation for young children to cultivate healthier habits for the future generation. According to the CDC “only 8 states require elementary schools to provide daily recess [and]… since the mid-2000s, up to 40% of school districts across the nation reduced or cut recess.” To add, technology has greatly diminished physical activity for children at home as “the days of the free-range childhood, where kids spend hours outside playing in local parks, building forts, fording streams and climbing trees, have been mostly replaced by video games, television watching and organized activities such as sports and clubs. We have traded green time for screen time — and it has had an impact on kids’ well-being and development” (Collin O’Mara). With that being the case, schools should be held accountable for redirecting the already ample amount of screen time children have even if that entails the assistance of mandates. 

SOURCES: 

- Claire McCarthy, MD. (2020, October 27). *6 reasons children need to play outside*. [https://www.health.harvard.edu/blog/6-reasons-children-need-to-play-outside-2018052213880](https://www.health.harvard.edu/blog/6-reasons-children-need-to-play-outside-2018052213880)
    
    
This source notes valuable reasons for why outdoor recess for children is vital In general. i.e. sunshine, exercise, executive function, taking risks, socialization 
    
- CDC. (n.d.). *Keep Recess in Schools*. [https://www.cdc.gov/healthyschools/physicalactivity/pdf/Recess_Data_Brief_CDC_Logo_FINAL_191106.pdf](https://www.cdc.gov/healthyschools/physicalactivity/pdf/Recess_Data_Brief_CDC_Logo_FINAL_191106.pdf)

Flyer/ document from the CDC on the importance of recess. Some important info: “Recess is a relatively easy and low cost way to help students be physically active. Recess also provides social, emotional, and academic achievement benefits.” ; “Only 8 states require elementary schools to provide daily recess”; “Since the mid-2000s, up to 40% of school districts across the nation reduced or cut recess.”

- Collin O’Mara. (2018, May 29). *Kids do not spend nearly enough time outside. Here’s how (and why) to change that.*[https://www.washingtonpost.com/news/parenting/wp/2018/05/30/kids-dont-spend-nearly-enough-time-outside-heres-how-and-why-to-change-that/](https://www.washingtonpost.com/news/parenting/wp/2018/05/30/kids-dont-spend-nearly-enough-time-outside-heres-how-and-why-to-change-that/)
    
    
Also highlights the shift in children's outdoor activity time due to technology: “Since the 1990s researchers have noticed a shift in how children spend their free time. The days of the free-range childhood, where kids spend hours outside playing in local parks, building forts, fording streams and climbing trees, have been mostly replaced by video games, television watching and organized activities such as sports and clubs. We have traded green time for screen time — and it has had an impact on kids’ well-being and development.”
    
- Monica Chierici, Elyse Powell, Rachel Manes. (2013). *Time to Play*. [https://media.nyam.org/filer_public/36/33/3633e2df-f7e2-415b-864b-8c50abdf08a3/mandatory-daily-active-recess-guide.pdf](https://media.nyam.org/filer_public/36/33/3633e2df-f7e2-415b-864b-8c50abdf08a3/mandatory-daily-active-recess-guide.pdf)

This source discusses the barriers preventing more outdoor time for children in NYC and how to overcome them with potential implementation strategies. 

- Brittany Shammas. (2019, March 7). *Time to Play: More State Laws Require Recess*. [https://www.edutopia.org/article/time-play-more-state-laws-require-recess](https://www.edutopia.org/article/time-play-more-state-laws-require-recess)
    
Information on the bills passed in certain states (very few) regarding recess and how those changes came about. Could be used as a tool to draw from when considering how such policies can take form in NYC.