---
author: "Christpher Soto"
title: "Community Parks Initiative"
date: "5/11/23"
---

On October 26, 2021, Mayor Bill de Blasio announced a 425 million dollar project with the Community Parks Initiative (CPI). Within the next ten years CPI guarantees to rebuild up to 10 community parks a year. 

The Community Parks initiative began in 2014. CPI began by reviewing data on New York City’s park investments from the last 20 years. The data showed that less advantaged communities had underinvested parks. These parks were empty, ruined, and outdated. In response CPI promises to renew these parks, but also connect its community to make sure a healthy environment emerges. CPI encourages communities to contribute by engaging them in the planning process by organizing social gathering events and activities. CPI also has a webpage if members of the community prefer to contribute remotely.  

Van Alst playground located in the borough of Queens was CPI’s first successful project. CPI renovated the children's playground by giving it a more fun and attractive look, and from that day on, CPI has renewed over 110 community parks across all five boroughs. The initiative focuses on repainting basketball courts, nets, handball courts, fences, remodeling playgrounds, swings, workout equipment, and gardens. Not to mention, CPI also provides service for the health and planning processes of communities. 

The Community Parks initiative is a very beneficial pathway for New York City because the people practice interconnectedness and safety. Community parks are rarely empty because they are much more approachable and clean. The parks are attractive to people of all ages. It's a place where people can go out and be active. A place where anyone can meet someone new and get along. The sense of danger is eliminated and parents feel safe having their kids around. As members of the community continue to provide maintenance and service to the park, the safety and interconnectedness status remains active. Applying such a change to underserved communities delivers a message that members of these communities are not forgotten.   

## Works cited

Community Parks Initiative — NYC Parks.*American Planning Association*,[https://www.planning.org/awards/2020/excellence/community-parks-initiative/](https://www.planning.org/awards/2020/excellence/community-parks-initiative/). Accessed 24 Mar. 2023.

*Community Parks Initiative Targeted Improvements : NYC Parks*.[https://www.nycgovparks.org/about/framework-for-an-equitable-future/community-parks-initiative/caring](https://www.nycgovparks.org/about/framework-for-an-equitable-future/community-parks-initiative/caring). Accessed 24 Mar. 2023.

Mayor de Blasio Announces Over $425 Million in New Funding for Transformative Community Parks Initia.*The Official Website of the City of New York*, 26 Oct. 2021,[http://www.nyc.gov/office-of-the-mayor/news/718-21/mayor-de-blasio-over-425-million-new-funding-transformative-community-parks](http://www.nyc.gov/office-of-the-mayor/news/718-21/mayor-de-blasio-over-425-million-new-funding-transformative-community-parks).

*NYC Parks: Framework for an Equitable Future*.*JSTOR*,[https://jstor.org/stable/community.29650592](https://jstor.org/stable/community.29650592). Accessed 24 Mar. 2023.

*How To Improve Community Parks in Your Neighborhood | LTC*.[https://littletikescommercial.com/blog/how-to-improve-community-parks/](https://littletikescommercial.com/blog/how-to-improve-community-parks/). Accessed 24 Mar. 2023.
