---
author: "Abigail Tenenbaum"
title: "City Meals-On-Wheels"
date: "5/11/23"
---

355 Lexington Ave #3, New York, NY 10017

This building is the site of City Meals-On-Wheels, a 501c3 organization and a registered NYC charity. Their goal is to tackle the issue of poverty in New York City, particularly among older New Yorkers. The organization all started in November 1981 with Gael Greene, a long-time restaurant critic who read about how food services in New York City didn’t work on weekends and holidays. These services being closed affected older New Yorkers’ ability to get food during the weekends. A month later, Greene gathered her friends in the food and hospitality industry; together, they created about 6,000 meals to share with elderly New Yorkers around Christmas time.

Poverty is a prevalent issue in New York City, especially among the older population. In 2017, A report from the Center for An Urban Future gathered data via survey from the senior population in New York State. The senior population in New York State grew 31%, while the state’s 65-under population decreased by 2%. In New York City, most of the increase in the elder population is due to an aging immigrant population. In regards to poverty levels, New York City’s 65+ community has a poverty rate of 20%. The study also reported higher poverty rates among Latine, Asian, and Black senior communities. 

Since late 1981, City Meals-On-Wheels has strove to deliver food to older New Yorkers in need. They’re open on weekends and most holidays, but on the holidays they do close on, they give out food in advance so that those in need get food. In 2011, the Mobile Food Pantry started so that those who couldn’t walk to get groceries or the meals themselves were delivered the food at their doorstep.

Besides food, the organization also has programs that support the elderly in other aspects of life. The Friendly Visiting Program addresses the loneliness and isolation issue among the elderly. According to the official City Meals-On-Wheels website, 57% of meal recipients live alone, 40% almost never leave home, and 8% have no one to talk to. The Friendly Visiting Program tackles this by pairing “caring individuals with homebound elderly neighbors in need of companionship.” Each volunteer dedicates an hour a week for at least 6 months, with a flexible schedule determined between the volunteer and their match. Other forms of social service include sending handmade cards for special occasions and making weekly phone calls to meal recipients. 

Since 1981, City Meals-On-Wheels has delivered over 67 million meals to the older NYC population. Their food and social outreach programs make them wonderful support for elderly New Yorkers. City Meals-On-Wheels is a wonderful example of community support and organization that comes together to help a population in need. 

## Sources

“CityMeals-On-Wheels,” n.d. [https://www.citymeals.org/about-us/what-we-deliver](https://www.citymeals.org/about-us/what-we-deliver).

Greer S, Adams L, Toprani A, Hinterland K, Dongchung TY, Brahmbhatt D, Miranda T, Guan QX, Kaye K, Gould LH. Health of Older Adults in New York City; 2019; 1-32. [https://www.nyc.gov/assets/doh/downloads/pdf/episrv/2019-older-adult-health.pdf](https://www.nyc.gov/assets/doh/downloads/pdf/episrv/2019-older-adult-health.pdf)

“Hope for New York,” n.d. [https://www.hfny.org/affiliates](https://www.hfny.org/affiliates).

Mercado, Angely, and Roshan Abraham. “A Snapshot of Poverty Among Older NYers Shows Pockets of Deep Need.” *CityLimits*, February 28, 2019. [https://citylimits.org/2019/02/28/aging-boom-poverty/](https://citylimits.org/2019/02/28/aging-boom-poverty/).

Lydia DePillis. “An Uptick in Elder Poverty: A Blip, or a Sign of Things to Come?” *New York Times*, October 17, 2022. [https://www.nytimes.com/2022/10/17/business/economy/elder-poverty-seniors.html](https://www.nytimes.com/2022/10/17/business/economy/elder-poverty-seniors.html).
