---
author: "Niamh Zanghi"
title: "Homelessness in NYC"
date: "5/11/23"
---

Homelessness in New York City is a crisis. We are facing an unprecedented homeless population that beats the rate from the Great Depression. Tens of thousands of adults and children sleep in the city’s shelters every night, and this rate is significantly higher than it was ten years ago. Not much is being done by the city government to combat this, and what *is* being done is insufficient or not solving the problem. The lack of affordable housing drives homelessness, followed by eviction, overcrowded housing, domestic violence, job loss, and hazardous housing conditions. Homeless people come from every community district in New York City, proving that this is a widespread problem, and suffer from higher rates of mental illness and addiction disorders. All of this is true, but city surveys significantly under-represent homeless statistics.

The current mayor of New York City, Eric Adams, has implemented a new policy in his first years as mayor to combat homelessness. He has been conducting sweeps on city streets and subway stations and cars, taking the homeless people there to shelters. Despite his best efforts, only thirty percent of homeless people being swept are still in those shelters after a week, and the rest are released. That remaining seventy percent return to the streets, undoing any progress Mayor Adams has caused. Homeless advocates, mental health advocates, and police officers all disagree with his policy. Homeless advocates say that the policing and forced removal is not the correct approach, and, instead, there needs to be a health and housing lens when looking at the problem. Mental health advocates say that Mayor Adams’ policy is a human rights violation, and the city has the power to provide onsite mental health treatment in shelters and supported housing. Police officers say that the sweeping and extra policing of homeless people places liability on them in dangerous situations, and could be fuel for escalation.

Providing accessible and supportive housing is the best way to prevent and solve homelessness. In every trial, it has reduced the need for the solutions Mayor Adams is proposing: shelters, hospitals, psychiatric hospitals, and incarceration. It raises stability for tenants and reduces chronic homelessness for single adults. Economically, it has also been a boost. Real estate values rise in areas closest to supportive housing. Outside of statistics, supportive housing is just humane. Mayor Adams' solution of sweeping homeless people into shelters (which are dangerous and uncomfortable for anyone) ignores their basic human autonomy.

To end homelessness, there needs to be a streamlined connection between the city and state governments. Oftentimes, they are at odds with each other, which only furthers the homelessness crisis and the mistreatment of homeless people. With a united approach on homelessness, featuring supportive housing and treatment, then the New York City homelessness rate could finally lower.

## Sources

1) [**Quick & basic NYC homelessness facts**](https://www.coalitionforthehomeless.org/basic-facts-about-homelessness-new-york-city/) 

2) [**NYC statement w/ facts about the problem & solutions**](https://council.nyc.gov/data/homeless/) 

3) **[Report on Mayor Eric Adams’ homelessness policy](https://www.cnn.com/2022/12/03/politics/nyc-hospitalize-mentally-ill-what-matters/index.html)** 

4) [**Report on homelessness shelters in NYC**](https://www.youtube.com/watch?v=rAJD6TU2TaM) 

5) [**Solutions to NYC homelessness](https://www.coalitionforthehomeless.org/supportive-housing-ends-homelessness/)**