---
author: "Niamh Zanghi"
title: "Subway vendors being arrested"
---

In 2019, Govenor Andrew Cuomo began to crack down on New York City subway crime. In an effort to improve quality of life, he focused the New York Police Department on fare evasion and subway vendors. Since then, New York City subways have become flooded with NYPD. Despite this, the organization is in debt, and politicians have been looking for ways to earn more money. Cracking down on subway vendors looked like the answer. Mayor Eric Adams continued the initiative when he was inaugerated on January 1st, 2022.

In May 2022, a video of a subway vendor, María Falcon, getting handcuffed and arrested next to her cart of mangos went viral on Twitter. Outrage sparked from New Yorkers and non-New Yorkers alike. Falcon was an immigrant woman from Ecuador trying to make a living. Mayor Adams confronted this outrage by saying that, if subway vendors were allowed to continue, then greater risks will follow, such as propane tanks and barbeques in subway stations. This is rooted in the broken windows theory, which promotes cracking down on small crimes to prevent larger crimes. The broken windows theory is notorious for being ineffective, yet many police departments, including the NYPD, follow it.

The villification of subway vendors does nothing to stop crime. Falcon was arrested at Broadway Junction, a station in Brooklyn with five trains. It was notoriously dangerous, with violence and drugs being the norm. The NYPD rarely stops these crimes, but that did not stop them from arresting Falcon. If Mayor Adams really cared about subway crime, then why are people afraid of knives and subway pushers at Broadway Junction?

Food vendors like Falcon are not the only victims of this treatment. John Ajilo was a saxophonist at Herald Square station in Manhattan known for the tiny robot kittens he performs with. He is a beloved character that has been at Herald Square for decades. In June 2022, he was arrested and detained for hours overnight. Just like with Falcon, outraged sparked. A GoFundMe was launched and raised over \$110,000 for Ajilo's legal fees.

Mayor Adams defends this policing by saying that subway vendors and performers obstruct traffic flow. Specifically about vendors, he says that they need a liscense of sell food. However, it is immensely difficult to obtain a vending license because it is capped at 5,000 in New York City and there are 2,500 people on the waitlist.

[The Street Vendor Project](http://streetvendor.org) is a nonprofit that defends street vendors like the ones being harrassed in New York City subway stations. They say that subway vendors are part of New York City culture. Also, they say that subway vendors support the economy by responding to consumer demand. The Street Vendor Project's work includes helping subway vendors get liscenses so they do not have to fear the NYPD as much.

Arresting subway vendors and street performers is not the answer to subway crime. The NYPD is already overpowered, and this initiative will only harm more immigrant communities and communities of color.

## Learn More

[Adams Defends Police for Handcuffing Vendor Who Sold Mangoes in Subway - NYT](https://www.nytimes.com/2022/05/09/nyregion/subway-safety-food-vendor-brooklyn.html)

[Advocates decry the arrest of a fruit vendor in New Yorks subway after video goes viral - The Observers](https://observers.france24.com/en/americas/20220513-viral-video-showing-arrest-of-an-unlicensed-fruit-vendor-in-new-york-subway-outrages-advocates)

['Egregious acts of violence': why is Eric Adams cracking down on subway buskers and mango sellers? - The Guardian](https://www.theguardian.com/us-news/2022/jul/01/new-york-street-vendors-arrests-mayor-eric-adams-nypd)

[Arrest the mango merchants after you get the real bad guys - The New Yorker](https://nypost.com/2022/05/12/arrest-the-mango-merchants-after-you-get-real-bad-guys/)

[The NYC Subway Food Vendor Police Crackdown, Explained - Eater](https://www.eater.com/2019/11/19/20971122/subway-food-vendor-crackdown-nyc-mta-sf-bart)
